### ISSUE TITLE
App not launch(Unfortunately app has stopped)

### ISSUE THREAD

**Issue by raoulcimpean** [mapsplugin/cordova-plugin-googlemaps#1011]
I have this issue only with google maps plugin installed,and only after i updated from adnroid sdk manager this:
```
Android TV Intel x86 Atom System Image, Android API 23, revision 4 --
Android Wear ARM EABI v7a System Image, Android API 23, revision 4--
Android Wear Intel x86 Atom System Image, Android API 23, revision 4
 Intel x86 Atom_64 System Image, Android API 23, revision 
Intel x86 Atom System Image, Android API 23, revision 9
Android TV Intel x86 Atom System Image, Android API 22, revision 3
Intel x86 Atom_64 System Image, Android API 22, revision 5
 Intel x86 Atom System Image, Android API 22, revision 5
 Intel x86 Atom System Image, Android API 19, revision 5
Intel x86 Atom System Image, Android API 16, revision 2
 Intel x86 Atom System Image, Android API 15, revision 2
 Google APIs, Android API 19, revision 20
 Android Support Repository, revision 33
 Android Support Library, revision 23.2.1 (Obsolete)
 Google Play services, revision 30
 Google Repository, revision 28 ---
Android TV Intel x86 Atom System Image, Android API 24, revision 4
 Intel x86 Atom_64 System Image, Android API 24, revision 4
 Intel x86 Atom System Image, Android API 24, revision 4
```
I think is from Google play services...but i can`t make it run.
Logcat error:
```
Process: com.app.virbac_project, PID: 24704
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
            at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4591)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4531)
            at android.app.ActivityThread.access$1500(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5253)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744)
     Caused by: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
```

**Comment by wf9a5m75** [comment]
As the error "Unable to get provider com.google.firebase.provider.FirebaseInitProvider" says,
this error regards about Firebase, not Google Maps.
It is not related with this plugin.
