### ISSUE TITLE
Phonegap build failing

### ISSUE THREAD

**Issue by haisham** [mapsplugin/cordova-plugin-googlemaps#1099]
Since few hours, phonegap build is failing with following error:
```
Error - Plugin error (you probably need to remove plugin files from your app): //github.com/mapsplugin/cordova-plugin-googlemaps --var API_KEY_FOR_ANDROID=***** --var API_KEY_FOR_IOS=****": Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps" via git clone Using shallow clone Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps" checked out to git ref "master" at "30a28df".
Installing "cordova-plugin-googlemaps" at "1.3.9" for ios Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk" via git clone Using shallow clone Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk" checked out to git ref "master" at "5072dcd".
Installing "com.googlemaps.ios" at "2.0.1" for ios Error during processing of action! Attempting to revert... Failed to install 'com.googlemaps.ios':CordovaError: Uh oh! Cannot find resource file "/private/tmp/gimlet/2033856/project/cordova/plugins/com.googlemaps.ios/Subspecs/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform at handlers.resource-file.install (/private/tmp/gimlet/2033856/project/cordova/lib/plugman/pluginHandlers.js:53:48) at Object.ActionStack.process
(/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation
(/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20) at PluginManager.addPlugin
(/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17) at Api.addPlugin (/private/tmp/gimlet/2033856/project/cordova/Api.js:219:10) at handleInstall
(/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:580:6) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:384:20 at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done
(/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) Failed to install
'cordova-plugin-googlemaps':CordovaError: Uh oh! Cannot find resource file "/private/tmp/gimlet/2033856/project/cordova/plugins/com.googlemaps.ios/Subspecs/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform at handlers.resource-file.install (/private/tmp/gimlet/2033856/project/cordova/lib/plugman/pluginHandlers.js:53:48) at Object.ActionStack.process (/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation
(/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20) at PluginManager.addPlugin
(/private/tmp/gimlet/2033856/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17) at Api.addPlugin
(/private/tmp/gimlet/2033856/project/cordova/Api.js:219:10) at handleInstall
(/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:580:6) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:384:20 at _fulfilled
(/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done
(/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch
(/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) Uh oh! Cannot find resource file
"/private/tmp/gimlet/2033856/project/cordova/plugins/com.googlemaps.ios/Subspecs/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform - You can fix this here
```

**Comment by wf9a5m75** [comment]
Oh, sorry. It seems the PhoneGap Build failed to download the maps sdk.
I fixed the repository. Please try again.

**Comment by haisham** [comment]
Yes its working, Thanks a Lot!!!
