### ISSUE TITLE
googlemaps-cdv-plugin.js:117 'getMap' is not defined in GoogleMaps plugin.

### ISSUE THREAD

**Issue by adityagoel19** [mapsplugin/cordova-plugin-googlemaps#1164]
Strange enough everything was working fine for me when for one 'cordova run android' I could not see the map. Console gave me this error.

> googlemaps-cdv-plugin.js:117 'getMap' is not defined in GoogleMaps plugin.

I regenerated API key. Reinstalled the plugin, using npm and then also tried using git.
Then I created a new cordova project, just added his plugin and again the issue is reproduced.

I tried going back to the version of my code that was working flawlessly but that also doesn't work now. So guessing it is not my code problem.

I am new here. Please let me know if you need any more information.
Cordova version: 6.4.0

**Comment by adityagoel19** [comment]
Tried with cordova 6.3.1. Though it doesn't give the error but the map also doesn't show up.

**Comment by wf9a5m75** [comment]
The current version will be shutdown near the future.
Please use the v2-beta.
https://github.com/mapsplugin/cordova-plugin-googlemaps#version-20-beta

**Comment by adityagoel19** [comment]
Thanks, I tried the v2-beta. But now whenever I launch the app on the device, it crashes even before the splash page where the plugin is not even used.

```
10-30 14:15:26.056  2750  2750 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/<APP ID REMOVED>-2/base.apk)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:235)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.Activity.runOnUiThread(Activity.java:5524)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:101)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at <APP ID REMOVED>.dev.MainActivity.onCreate(MainActivity.java:39)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-30 14:15:26.056  2750  2750 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wf9a5m75** [comment]
The v2  does not work with the ionic wrapper

**Comment by adityagoel19** [comment]
I am not using Ionic. The issue comes when I add plugin cordova-plugin-request-network-accuracy. Remove the plugin and the app works fine. Both the plugins work fine without adding the other one but adding both of them is not working.

**Comment by wf9a5m75** [comment]
In that case, you need to choose one of them.

**Comment by adityagoel19** [comment]
I guess that's the only way. Using plugin cordova.plugins.diagnostic solve's the problem. Thanks for your help.
