### ISSUE TITLE
Map view not moving with the rest of the page

### ISSUE THREAD

**Issue by nimosza** [mapsplugin/cordova-plugin-googlemaps#1372]
I'm using jquery mobile and phonegap to create an app and since I've started trying to use phonegap build to create a release version of my app, I've been having the following problem:
When I scroll up and down on the page, the map view remains in a static position behind the content.
It's been working perfectly using the phonegap cli.
It's worth noting that I had to use version 1.3.9 of the plugin rather than version 1.4 to get it working with phonegap build.
I'm pretty much at my wits end and have started looking at alternatives to this plugin which is a path I really don't want to have to go down, as this plugin has worked perfectly up until now.

**Comment by wf9a5m75** [comment]
Did you try the plugin v2?

**Comment by nimosza** [comment]
Hi, yes I did. But it fails to build the app when I try to use v2. The log output is pasted below:
```
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-app-event" via npm
Installing "cordova-plugin-app-event" at "1.2.0" for android
Fetching plugin "cordova-plugin-camera" via npm
Installing "cordova-plugin-camera" at "2.4.0" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.1.0" for android
Subproject Path: CordovaLib
Plugin "cordova-plugin-compat" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.5" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "1.3.2" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "2.4.2" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
"plugman install --platform android --project /project --plugin https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --var API_KEY_FOR_ANDROID=###################": Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" via git clone
Using shallow clone
Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" checked out to git ref "multiple_maps" at "90a95c4".
Installing "cordova-plugin-googlemaps" at "2.0.0-beta" for android
Failed to install 'cordova-plugin-googlemaps':Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-googlemaps can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
    at PlatformMunger.add_plugin_changes (/project/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:169:19)
    at /project/cordova/node_modules/cordova-common/src/PluginManager.js:126:25
    at _fulfilled (/project/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:796:13)
    at /project/cordova/node_modules/q/q.js:857:14
    at runSingle (/project/cordova/node_modules/q/q.js:137:13)
    at flush (/project/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-googlemaps can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
```
Thanks for your help.

**Comment by wf9a5m75** [comment]
Oh, sorry, I forgot this issue.

You can install with --force option.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1296#issuecomment-278446860

**Comment by nimosza** [comment]
Thanks, I'll try that.
