### ISSUE TITLE
can't run android version  java.lang.NoSuchMethodError: No static method zzA

### ISSUE THREAD

**Issue by Sohib** [mapsplugin/cordova-plugin-googlemaps#1400]
after installing the plugin and running my app i got this error 

```
      java.lang.NoSuchMethodError: No static method zzA(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/com.Greeb.DriverApp-2/base.apk)
                                                                         at com.google.android.gms.maps.internal.zzai.zzbq(Unknown Source)
                                                                         at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                                         at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:238)
                                                                         at android.app.Activity.runOnUiThread(Activity.java:5858)
                                                                         at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:104)
                                                                         at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                                         at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                                                                         at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                                                                         at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                                                                         at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
                                                                         at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                                                                         at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                                                                         at com.Greeb.DriverApp.MainActivity.onCreate(MainActivity.java:39)
                                                                         at android.app.Activity.performCreate(Activity.java:6673)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2786)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:173)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6459)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

**Comment by wf9a5m75** [comment]
Does you Android have Google Play Services?

**Comment by b4tch** [comment]
I have the same problem, did you resolve this?

**Comment by ThonyBG** [comment]
I solve issue like that upgrading to the last plugin version
