### ISSUE TITLE
app stopped . 

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1409]
after updating some elements in SDK manager . i'm not able to complie / run the app.also i try with a project that was working before .. i'm getting [APP Name ] Stopped directly after launching.
( this error happened only when the google maps plugin is installed )

this is the logcat

```
04-19 01:51:02.995 2590-2713/? I/PackageManager: Removing non-system package:com.parking.tunisie
04-19 01:51:04.680 2590-2713/? I/PackageManager: Package com.parking.tunisie codePath changed from /data/app/com.parking.tunisie-2.apk to /data/app/com.parking.tunisie-1.apk; Retaining data and using new
04-19 01:51:08.650 10340-10340/? D/CapabilityManagerService: The package(com.parking.tunisie) updated
04-19 01:51:10.135 4162-4162/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] PackageName : com.parking.tunisie, true, false
04-19 01:51:10.770 3482-12339/? D/Wear_Controller: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=com.parking.tunisie
04-19 01:51:10.790 3482-6222/? E/Drive.UninstallOperation: Package still installed com.parking.tunisie
04-19 01:51:12.740 3482-12340/? D/Wear_Controller: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=com.parking.tunisie
04-19 01:51:13.280 12394-12394/com.parking.tunisie D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 0ms
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/CordovaLog: Changing log level to DEBUG(3)
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/CordovaActivity: Apache Cordova native platform version 6.1.2 is starting
04-19 01:51:13.345 12394-12394/com.parking.tunisie D/CordovaActivity: CordovaActivity.onCreate()
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
04-19 01:51:13.355 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 28: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
04-19 01:51:13.355 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0009
04-19 01:51:13.355 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method org.apache.cordova.CordovaInterfaceImpl.requestPermissions
04-19 01:51:13.355 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 72: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
04-19 01:51:13.355 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a
04-19 01:51:13.360 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.engine.SystemWebViewEngine.enableRemoteDebugging
04-19 01:51:13.360 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve static method 11672: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
04-19 01:51:13.360 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x71 at 0x0001
04-19 01:51:13.360 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method org.apache.cordova.engine.SystemWebViewEngine.initWebViewSettings
04-19 01:51:13.360 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11660: Landroid/webkit/WebSettings;.setMediaPlaybackRequiresUserGesture (Z)V
04-19 01:51:13.360 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0080
04-19 01:51:13.370 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method org.apache.cordova.engine.SystemWebView.evaluateJavascript, referenced from method org.apache.cordova.engine.SystemWebViewEngine.evaluateJavascript
04-19 01:51:13.370 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 22052: Lorg/apache/cordova/engine/SystemWebView;.evaluateJavascript (Ljava/lang/String;Landroid/webkit/ValueCallback;)V
04-19 01:51:13.370 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
04-19 01:51:13.390 4294-4294/? I/Finsky: [1] com.google.android.finsky.utils.as.run(3288): Package state data is missing for com.parking.tunisie
04-19 01:51:13.515 12394-12394/com.parking.tunisie I/webclipboard: clipservice: android.sec.clipboard.ClipboardExManager@425835d0
04-19 01:51:13.530 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.engine.SystemCookieManager.<init>
04-19 01:51:13.530 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11623: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
04-19 01:51:13.530 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x001b
04-19 01:51:13.530 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.CookieManager.flush, referenced from method org.apache.cordova.engine.SystemCookieManager.flush
04-19 01:51:13.530 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11617: Landroid/webkit/CookieManager;.flush ()V
04-19 01:51:13.530 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
04-19 01:51:13.540 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.engine.SystemWebViewClient.onReceivedClientCertRequest
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11677: Landroid/webkit/WebViewClient;.onReceivedClientCertRequest (Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V
04-19 01:51:13.540 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6f at 0x001a
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/PermissionRequest;)
04-19 01:51:13.545 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.PermissionRequest.getResources, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onPermissionRequest
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11635: Landroid/webkit/PermissionRequest;.getResources ()[Ljava/lang/String;
04-19 01:51:13.545 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
04-19 01:51:13.545 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onShowFileChooser
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11640: Landroid/webkit/WebChromeClient$FileChooserParams;.createIntent ()Landroid/content/Intent;
04-19 01:51:13.545 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0000
04-19 01:51:13.560 12394-12407/com.parking.tunisie V/webkit: BrowserFrame constructor: this=Handler (android.webkit.BrowserFrame) {4257d390}
04-19 01:51:13.560 12394-12394/com.parking.tunisie D/SystemWebViewEngine: CordovaWebView is running on device made by: samsung
04-19 01:51:13.575 12394-12394/com.parking.tunisie I/SystemWebViewEngine: Disabled addJavascriptInterface() bridge since Android version is old.
04-19 01:51:13.575 12394-12394/com.parking.tunisie D/PluginManager: init()
04-19 01:51:13.615 12394-12394/com.parking.tunisie D/dalvikvm: GC_FOR_ALLOC freed 205K, 12% free 8228K/9287K, paused 31ms, total 31ms
04-19 01:51:13.620 12394-12394/com.parking.tunisie I/dalvikvm-heap: Grow heap (frag case) to 9.421MB for 601616-byte allocation
04-19 01:51:13.645 12394-12407/com.parking.tunisie D/dalvikvm: GC_FOR_ALLOC freed 1K, 12% free 8814K/9927K, paused 26ms, total 26ms
04-19 01:51:13.695 12394-12397/com.parking.tunisie D/dalvikvm: GC_CONCURRENT freed 5K, 12% free 8828K/9927K, paused 12ms+2ms, total 51ms
04-19 01:51:13.705 4823-5000/? I/cm.log.servpro: [InstallMonitorReceiver][D]/ scanRemainFile: com.parking.tunisie true
04-19 01:51:13.705 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0
04-19 01:51:13.710 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0, fromUser = false
04-19 01:51:13.710 12394-12394/com.parking.tunisie D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
04-19 01:51:13.715 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0
04-19 01:51:13.720 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0, fromUser = false
04-19 01:51:13.720 12394-12394/com.parking.tunisie D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 10000
04-19 01:51:13.770 12394-12394/com.parking.tunisie I/CordovaLog: Changing log level to 5
04-19 01:51:13.775 12394-12394/com.parking.tunisie E/dalvikvm: Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.zzg.zzaK
04-19 01:51:13.775 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve check-cast 245 (Landroid/os/UserManager;) in Lcom/google/android/gms/common/zzg;
04-19 01:51:13.775 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x1f at 0x000c
04-19 01:51:13.780 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzg.zzz
04-19 01:51:13.780 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 477: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
04-19 01:51:13.780 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
04-19 01:51:13.780 12394-12394/com.parking.tunisie E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzadf.zzg
04-19 01:51:13.780 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve check-cast 24 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/internal/zzadf;
04-19 01:51:13.780 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x1f at 0x0010
04-19 01:51:13.790 12394-12394/com.parking.tunisie D/GoogleMapsPlugin: ----> checkGooglePlayServices = true
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: DexOpt: method is in an interface
04-19 01:51:13.795 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method com.google.android.gms.dynamic.zze.zzA, referenced from method com.google.android.gms.maps.internal.zzai.zzbq
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve static method 13871: Lcom/google/android/gms/dynamic/zze;.zzA (Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd;
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY:  rejecting opcode 0x71 at 0x001d
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY:  rejected Lcom/google/android/gms/maps/internal/zzai;.zzbq (Landroid/content/Context;)Lcom/google/android/gms/maps/internal/zzc;
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: Verifier rejected class Lcom/google/android/gms/maps/internal/zzai;
04-19 01:51:13.795 12394-12394/com.parking.tunisie D/AndroidRuntime: Shutting down VM
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41ca22a0)
04-19 01:51:13.795 12394-12394/com.parking.tunisie E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.VerifyError: com/google/android/gms/maps/internal/zzai
                                                                         at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                                         at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:238)
                                                                         at android.app.Activity.runOnUiThread(Activity.java:4767)
                                                                         at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:104)
                                                                         at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                                         at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                                                                         at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                                                                         at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                                                                         at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
                                                                         at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                                                                         at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                                                                         at com.parking.tunisie.MainActivity.onCreate(MainActivity.java:39)
                                                                         at android.app.Activity.performCreate(Activity.java:5207)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2085)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
                                                                         at android.app.ActivityThread.access$700(ActivityThread.java:140)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4947)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bigbossmaher** [comment]
when i execute ant in cmd i get
Buildfile: build.xml does not exist!
Build failed

screen shot of SDK
![capture2](https://cloud.githubusercontent.com/assets/15154710/25157791/5f3520a2-249b-11e7-835e-7945d05e25bc.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15154710/25157792/5f37c01e-249b-11e7-9d07-d2b635ab2e9f.PNG)

**Comment by wf9a5m75** [comment]
Does your android has the Google Play Serivces?
The output of logcat does not contain the following lines:
```
I/Google Maps Android API( 4208): Google Play services client version: 9452000
I/Google Maps Android API( 4208): Google Play services package version: 9452230
```

**Comment by bigbossmaher** [comment]
i get this error on the tablet + emulator

**Comment by bigbossmaher** [comment]
google play services is intalled as you see in the screan above

**Comment by bigbossmaher** [comment]
the logcat that i give you is only for com.parking.tunisie not all the device

**Comment by wf9a5m75** [comment]
No, you are misunderstand.
Google Play Services is not library, that's different apk from Google.

Open this URL on your tablet, then install it if it's not installed.
https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en

**Comment by wf9a5m75** [comment]
If the google play services is already installed, it might be your api key is incorrect.
```
  java.lang.VerifyError: com/google/android/gms/maps/internal/zzai
```

**Comment by wf9a5m75** [comment]
```
at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:238)
```
CordovaGoogleMaps.java:238 is here.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/69937fe0b9c62f7d3de8b531880cb32f1953dd7d/src/android/plugin/google/maps/CordovaGoogleMaps.java#L238

It's just initializing the Google Maps Android API v2.
If fails here, it means your API key is incorrect most time.

**Comment by bigbossmaher** [comment]
i was working with this tablet before , i was able to run apps that used your plugin .
i have an old generated apk .. i installed it , it works.
i think the problem in compiling . because i have restored a working backup that i'm sure 100/100 that is working but it fails

**Comment by wf9a5m75** [comment]
Do you really use the same api key with the same android adb key?

**Comment by bigbossmaher** [comment]
i did not understad this

**Comment by bigbossmaher** [comment]
listen to me . i was using you plugin without any problem for 3 or 4 months . the old generated APK are working . but when i re-compile the cordova project for those APK it fails

**Comment by wf9a5m75** [comment]
When you developed your app before, you definitely did this step, because without this, you can not create your app.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/Installation/macosx/README.md#3-only-for-android-displaying-the-debug-certificate-fingerprint

In this step, you specify `~/.android/debug.keystore` (or your release key), then you registered your SHA-1 fingerprint to Google.
If you use the same api key, you have to use the same keystore.

**Comment by wf9a5m75** [comment]
> i was using you plugin without any problem for 3 or 4 months

Ok, you can check the commit log of this repository on the multiple_maps.

I did only a few commit for small fixes.

**Comment by wf9a5m75** [comment]
`java.lang.VerifyError` means API key is incorrect.

**Comment by bigbossmaher** [comment]
i was working with the same api for a long time . how can i change the api in the project

**Comment by wf9a5m75** [comment]
I don't know, but it's definitely your environment problem.
It's not plugin's problem.
Without new information, I have no more advise (run-out).

**Comment by bigbossmaher** [comment]
thanks a lot  . i just send you by email a zip file of my cordova projet . it was working before , could you test it

**Comment by wf9a5m75** [comment]
ok

**Comment by bigbossmaher** [comment]
i changed the the api key ( i made search  / replace in all file of projet ) the same thing .

**Comment by wf9a5m75** [comment]
By the way, let me confirm one thing before test.
What did you change on your project at this time?
For example, install another plugins or just change your code.

**Comment by bigbossmaher** [comment]
i think i make update for android SDK .
but the project that i give you is working . and i use it evry time when i have a trouble

**Comment by wf9a5m75** [comment]
I just execute your project `cordova run android`, and it worked.

**Comment by bigbossmaher** [comment]
i made cordova run android and i get " Parking Tunisie s'est arreté " it mean stopped.
both on emulator and tablet

**Comment by wf9a5m75** [comment]
![screenshot_20170418-175611](https://cloud.githubusercontent.com/assets/167831/25158884/842dbbde-2460-11e7-9ca3-1dc6c698993d.png)

**Comment by bigbossmaher** [comment]
yes i konw it is working . i used this project many times as a backup .
why i'm not able to generate a new apk ?

**Comment by wf9a5m75** [comment]
Um, I have no idea.

**Comment by wf9a5m75** [comment]
Did you try to build your project on another PC?

**Comment by bigbossmaher** [comment]
is the SDK manager config is correct ( see screen shots ).
i'm going now to delete all things and install them again

**Comment by bigbossmaher** [comment]
i tried to create a new project with new api , i get this error when installing the plugin , do yo have any idea why i'm gtting this ?
it is a new cordova project
![capture](https://cloud.githubusercontent.com/assets/15154710/25176801/64e4a278-24f7-11e7-827b-509e8b792c62.PNG)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1296#issuecomment-278446860

**Comment by bigbossmaher** [comment]
i think your google maps plugin can not work with https://github.com/cowbell/cordova-plugin-geofence

because when i delete one of them the app is work
can you tell me why ?

**Comment by wf9a5m75** [comment]
Could you search before asking?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues?q=is%3Aissue+geofence+is%3Aclosed

**Comment by bigbossmaher** [comment]
i tried many solutions , i also re-installed windows then all other tools like android sdk and cordova .
i alaways get the same error . the app works only if i remove your plugin or geofence plugin.
i'm not enable to build apps since i have apdated sdk tools.
as it is working for you. can you give me the build tools version / cordova version / platforms tools version and other tools versions that can cause this issue

**Comment by wf9a5m75** [comment]
Um, could you share your project on github (or bitbucket ...etc)?

**Comment by bigbossmaher** [comment]
thanks a lot , i fixed the issue buy changing
cordova.system.library.1=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.2=com.google.android.gms:play-services-location:10.0.0
cordova.system.library.3=com.google.android.gms:play-services-location:+

with

cordova.system.library.1=com.google.android.gms:play-services-maps:9.8.0
cordova.system.library.2=com.google.android.gms:play-services-location:9.8.0
cordova.system.library.3=com.google.android.gms:play-services-location:9.8.0
