### ISSUE TITLE
seticon issue

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1423]
is this issue comes from seticon method ?

```
04-28 20:31:18.088 1609-1650/system_process E/InputDispatcher: channel '4684d86 com.parking.tunisie/com.parking.tunisie.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-28 20:31:23.340 4829-4829/com.parking.tunisie E/GoogleMapsPlugin: ===> onConnected
04-28 20:31:24.484 4829-4829/com.parking.tunisie E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.parking.tunisie, PID: 4829
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms.maps.model.BitmapDescriptor)' on a null object reference
                                                                       at plugin.google.maps.PluginMarker$12.onPostExecute(PluginMarker.java:919)
                                                                       at plugin.google.maps.PluginMarker$12.onPostExecute(PluginMarker.java:818)
                                                                       at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-28 20:33:11.911 2341-2807/com.google.android.gms E/Drive.UninstallOperation: Package still installed com.parking.tunisie
04-28 20:33:13.070 5077-5121/com.parking.tunisie E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
```

**Comment by wf9a5m75** [comment]
It seems the plugin could not read icon file for some reason.
Please confirm the image url or path.

**Comment by wf9a5m75** [comment]
ping

**Comment by bigbossmaher** [comment]
Just give some time , i will go back to you shortly , thank you

**Comment by wf9a5m75** [comment]
Ok.

**Comment by wf9a5m75** [comment]
By the way, did you execute `$> cordova prepare` or `$> ionic prepare`?

**Comment by bigbossmaher** [comment]
Just i have some exams , i will go back to you shortly ;)

Le mer. 10 mai 2017 à 20:27, Masashi Katsumata <notifications@github.com> a
écrit :

**Comment by bigbossmaher** [comment]
i solved the issue by moving the code to another place , but it seems not not working . i want tomakes the icons small , but when zooming-in it become bigger
is that possible ?

**Comment by wf9a5m75** [comment]
What are you talking about? This plguin does not change the icon size except your code specify the size.
Please provide more information, such as video, or your code.

**Comment by bigbossmaher** [comment]
in my app , when the zoom is out , i want that the marker icons shoud be small so that all markers appears. when the user zoom in more , the marker icon become more bigger . is that possible ? it is used here
https://www.parking.tn/

**Comment by wf9a5m75** [comment]
That URL uses marker clustering feature. Not icon size.
And this plugin does not provide the marker clustering feature.

**Comment by bigbossmaher** [comment]
Thank you , i have a question .
When a popup is appear over the map and be shown for sometime , It is
clickble only for the second try

Le sam. 13 mai 2017 à 17:11, Masashi Katsumata <notifications@github.com> a
écrit :

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by wf9a5m75** [comment]
Ping
