### ISSUE TITLE
NullPointerException occurs sometimes when destroying map

### ISSUE THREAD

**Issue by sam2x** [mapsplugin/cordova-plugin-googlemaps#1434]
Hey,

Can we prevent the following fatal exception by checking that object reference isnt null ? 

```
com.xxxx.xxxx E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.xxxx.xxxx, PID: 996
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference
 at plugin.google.maps.PluginMarker$3.run(PluginMarker.java:133)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:7331)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Occurs occasionally in [PluginMarker.java:133](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginMarker.java#L133) when i left the map view. I think "race condition" occurs (async code), so this code got called **after** object is nullified. If we can assure "priority" execution during cleanup, it will be interesting for stability, but i have no idea how to do this in async context.

Adding a safe check like you did on other part of the code should solve the issue :

        if (objects == null) {
          return;
        }

Regards,

**Comment by wf9a5m75** [comment]
Thanks.
