### ISSUE TITLE
Can’t install plugin on IOS platform

### ISSUE THREAD

**Issue by ferminako** [mapsplugin/cordova-plugin-googlemaps#1436]
Hi,

As I try to install the plugin on my ios proyect running  ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="xxx" --variable API_KEY_FOR_IOS="xxx"

I get: Installing "cordova-plugin-googlemaps" for ios

Installing "com.googlemaps.ios" for ios

Error during processing of action! Attempting to revert...

Failed to install 'com.googlemaps.ios': CordovaError: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform
    at install (/Users/aehn/Documents/cs_app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:61:23)
    at Object.process (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

Failed to install 'cordova-plugin-googlemaps': CordovaError: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform
    at install (/Users/aehn/Documents/cs_app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:61:23)
    at Object.process (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

Error: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform

Any idea?

Your system information:

Cordova CLI: 7.0.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3.2 Build version 8E2002

Thanks!

**Comment by wf9a5m75** [comment]
Please try to install with `--nofetch` option.

**Comment by ferminako** [comment]
I've just tried and I get this error:
`Installing "cordova-plugin-googlemaps" for ios


Plugin dependency "com.googlemaps.ios@2.2.0" already fetched, using that version.


Installing "com.googlemaps.ios" for ios


Error during processing of action! Attempting to revert...


Failed to install 'com.googlemaps.ios': CordovaError: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform
    at install (/Users/aehn/Documents/cs_app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:61:23)
    at Object.process (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

Failed to install 'cordova-plugin-googlemaps': CordovaError: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform
    at install (/Users/aehn/Documents/cs_app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:61:23)
    at Object.process (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/aehn/Documents/cs_app/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:619:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:379:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)


Error: Uh oh!
Cannot find resource file "/Users/aehn/Documents/cs_app/plugins/com.googlemaps.ios/Maps/Frameworks/GoogleMaps.framework/Versions/A/Resources/GoogleMaps.bundle" for plugin com.googlemaps.ios in iOS platform`

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1435#issuecomment-299580754

**Comment by ferminako** [comment]
Thanks
