### ISSUE TITLE
Maps v2 custom Marker

### ISSUE THREAD

**Issue by adriallongarriu** [mapsplugin/cordova-plugin-googlemaps#1483]
Hello,
I create a Ionic 2 app and I want a marker with custom icon and event MARKER_CLICK.

When i change the icon the map show my icon but the event is not trigger.
Add Marker without icon event works.

My code:
```
icon = {
    url: 'www/assets/img/map/cluster.png',
    size: {
        width: 32,
        height: 32
    }
};
let latLang = new plugin.google.maps.LatLng(c.geometry.coordinates[1], c.geometry.coordinates[0]);

this.map.addMarker({
    position: latLang,
    icon: icon
}, function (marker) {
    marker.on(plugin.google.maps.event.MARKER_CLICK, function () {
        this.map.moveCamera({
            target: latLang,
            zoom: (newZoom + 1)
        });
    });
});
```

Android studio show this errors when i add a Marker with custom icon:

> W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
> W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
> W/System.err:     at plugin.google.maps.PluginMarker.setIcon_(PluginMarker.java:1097)
> W/System.err:     at plugin.google.maps.PluginMarker.access$300(PluginMarker.java:40)
> W/System.err:     at plugin.google.maps.PluginMarker$4$1.run(PluginMarker.java:308)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> W/System.err:     at java.lang.Thread.run(Thread.java:818)
> W/System.err:     at plugin.google.maps.PluginMarker.setIcon_(PluginMarker.java:1097)
> W/System.err:     at plugin.google.maps.PluginMarker.access$300(PluginMarker.java:40)
> W/System.err:     at plugin.google.maps.PluginMarker$4$1.run(PluginMarker.java:308)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> W/System.err:     at java.lang.Thread.run(Thread.java:818)
> W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
> W/System.err:     at plugin.google.maps.PluginMarker.setIcon_(PluginMarker.java:1097)
> W/System.err:     at plugin.google.maps.PluginMarker.access$300(PluginMarker.java:40)
> W/System.err:     at plugin.google.maps.PluginMarker$4$1.run(PluginMarker.java:308)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
> W/System.err:     at plugin.google.maps.PluginMarker.setIcon_(PluginMarker.java:1097)
> W/System.err:     at 	at plugin.google.maps.PluginMarker.access$300(PluginMarker.java:40)
> W/System.err: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> W/System.err:     at 	at plugin.google.maps.PluginMarker$4$1.run(PluginMarker.java:308)java.lang.Thread.run(Thread.java:818)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> W/System.err:     at java.lang.Thread.run(Thread.java:818)
> I/chromium: [INFO:CONSOLE(130)] "Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (130)
> I/chromium: [INFO:CONSOLE(130)] "Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (130)
> I/chromium: [INFO:CONSOLE(130)] "Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (130)
> I/chromium: [INFO:CONSOLE(130)] "Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (130)
> I/chromium: [INFO:CONSOLE(130)] "Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference", source: file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/BaseClass.js (130)
>

**Comment by adriallongarriu** [comment]
I try a cluster system and i use map.clear() every time user change the camerPosition.
Some time i get this error java.lang.IllegalArgumentException: Unmanaged descriptor.
I think it's because i delete markers while they are being created.
The problem is similar to issue #1485 
I close this issue.
