### ISSUE TITLE
【Monaca】Androidでのビルドに失敗する Version 2.0 Beta

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#1529]
Monacaでのビルド時に以下のエラーで失敗してしまいます。
プラグインのバージョンはmultiple_mapブランチの最新です。

こちら原因等お分かりでしょうか？
また以下のエラーログ内に「Line:0、Column:113」とありますが、どのファイルのことを指しているのか分かりますでしょうか？

```
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add /tmp/monaca/595ef3ca8034517e566870d0/output/plugins/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY ANDROID API KEY" --variable API_KEY_FOR_IOS="MY IOS API KEY" --variable LOCATION_WHEN_IN_USE_DESCRIPTION="My custom when in use message" --variable LOCATION_ALWAYS_USAGE_DESCRIPTION="My custom always usage message"
Installing "cordova-plugin-googlemaps" for android
Failed to install 'cordova-plugin-googlemaps':Error: Invalid attribute name
Line: 0
Column: 113
Char: "
    at error (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/sax/lib/sax.js:364:22)
    at Object.write (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/sax/lib/sax.js:883:14)
    at XMLParser.feed (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:606:13)
    at ConfigFile_graft_child [as graft_child] (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:101:32)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:84:34)
    at PlatformMunger.add_plugin_changes (/private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:160:14)
    at /private/tmp/monaca/595ef3ca8034517e566870d0/project/platforms/android/cordova/Api.js:219:14
```

よろしくお願いいたします。

**Comment by wf9a5m75** [comment]
うーん、このログだと何が悪いか分からないですね。
なにかのXMLファイルのパースが失敗したみたいですね

可能性として、config.xmlが悪いか、もしかしたらplugin.xmlが悪いかもしれないですね。

Monacaのプロジェクトに招待していただければ、もう少し分かるかもしれませんので、もし問題なければ招待していただけると幸いです。
NDAが必要でしたらPDFで送っていただければサインしますよ。
アカウントはgithubのメールアドレスです

**Comment by yesman99** [comment]
早速のご連絡ありがとうございます。

試しに[v2.0 example](https://github.com/mapsplugin/v2.0-demo)でもプロジェクトを作成して、multiple_mapブランチのプラグインを入れてビルドを試みましたが同じエラーが発生しました。

Monacaプロジェクトに招待を送りました。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by wf9a5m75** [comment]
ありがとうございます。ただ権限がちょっと弱いようです。

![screen shot 2017-07-06 at 11 27 49 pm](https://user-images.githubusercontent.com/167831/27945640-c1655b26-62a2-11e7-8974-21521a4d77fe.png)

同時並行で、Monacaを運営しているアシアル株式会社さんにお願いをして、期間限定のトライアルをさせてもらえることになりました。
なので、まずは私のほうで空プロジェクトを作って、再現するかどうかを確認してみます。
それを踏まえて @yesman99 さんのプロジェクトをチェックします。

アメリカ時間（現在23時）なので明日の作業になりますので、少しお待ちください。

**Comment by yesman99** [comment]
招待について、開発者権限とテスター権限の２種類があったのですが、githubのメールアドレスではテスター権限しか招待できませんでした。

まずは空プロジェクトで確認いただける点、了解しました。

遅い時間にも関わらずご対応いただきありがとうございます。
ご連絡お待ちしております。

**Comment by wf9a5m75** [comment]
>招待について、開発者権限とテスター権限の２種類があったのですが、githubのメールアドレスではテスター権限しか招待できませんでした。

これはたぶん、招待をしていただいた時点ではPlanがフリー版だったからかもしれません。
今はProプランに切り替わっていますので、もしかしたら開発者権限で招待ができるかもしれません。

空プロジェクトでビルドすると、とりあえずできましたが、デバッガで実行しているせいか、地図が表示されないですね。どうゆうわけか。
明日、詳しく調べてみます。

**Comment by wf9a5m75** [comment]
おはようございます。やり直してみましたが、ちゃんと出来ましたね。
カスタムビルドのデバッグとも相性良く動いています。

![1529](https://user-images.githubusercontent.com/167831/27970946-ad441106-6305-11e7-8030-28c470d556e2.gif)

プロジェクトをエクスポートしましたので、これをインポートしてテストをしてみてください。
[hello-googlemaps-for-monaca.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1131916/hello-googlemaps-for-monaca.zip)

**Comment by wf9a5m75** [comment]
プラグインのインストールですが、config.xmlではなく、メニューからインポートするといいと思います。
そうするとデバッガをビルドするときに、組み込まれるようです。

![screen shot 2017-07-07 at 11 20 06 am](https://user-images.githubusercontent.com/167831/27971185-89ab7b98-6306-11e7-910b-971281a95dbf.png)

**Comment by yesman99** [comment]
ご確認いただきありがとうございました。
いただいたプロジェクトを参考に、原因の判明まで行くことができました。

原因として、MonacaでのCordovaプラグイン管理にて、インストールパラメータ（API_KEY_FOR_ANDROID等）を設定する際に、値をダブルクオーテーションで囲ってしまっていたためでした。
（Monacaでは値をダブルクオーテーションで囲む必要はありませんでした）

こちらクローズとさせていただきます。
ありがとうございました。

**Comment by wf9a5m75** [comment]
原因を解明していただいてありがとうございます。そんなことが原因でしたか。あとで私も再現するかテストして、アシアル社さんにフィードバックしたいと思います。

**Comment by wf9a5m75** [comment]
ダブルクォーテーション付けたら確かに再現しますね。しかもこのエラーログでは確かに分からないです。フィードバックをしておきます。
