### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1544]
the app is crashed

```
  --------- beginning of crash
07-10 23:20:39.776 6545-6545/com.parking.tunisie E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.parking.tunisie, PID: 6545
                                                                   java.lang.IllegalArgumentException: Unmanaged descriptor
                                                                       at com.google.maps.api.android.lib6.common.k.b(:com.google.android.gms.DynamiteModulesB:162)
                                                                       at com.google.maps.api.android.lib6.impl.o.c(:com.google.android.gms.DynamiteModulesB:75)
                                                                       at com.google.maps.api.android.lib6.impl.db.a(:com.google.android.gms.DynamiteModulesB:334)
                                                                       at com.google.android.gms.maps.model.internal.q.onTransact(:com.google.android.gms.DynamiteModulesB:204)
                                                                       at android.os.Binder.transact(Binder.java:499)
                                                                       at com.google.android.gms.maps.model.internal.zzf$zza$zza.zzM(Unknown Source)
                                                                       at com.google.android.gms.maps.model.Marker.setIcon(Unknown Source)
                                                                       at plugin.google.maps.PluginMarker$3.run(PluginMarker.java:149)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

- cordova-plugin-googlemaps 2.0.0-beta2-20170705-1715

**Comment by wf9a5m75** [comment]
This occurs because you did something (such as setIcon()) for the marker which is already removed.

**Comment by wf9a5m75** [comment]
Well, regarding of the version `cordova-plugin-googlemaps 2.0.0-beta2-20170705-1715`, 
it seems your app fails at here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/c5c46fa62cf96108ebca2d083893b43271b52d24/src/android/plugin/google/maps/PluginMarker.java#L149

The `pluginMarker.clear()` method is invited by `PluginMap.claer()`.
It means you executed `map.clear()`.
But the marker is already removed.

So I guess you do something like this:

```js
map.remove();
map.clear();
```

or 

```js
map.clear();
map.remove();
```

**Comment by wf9a5m75** [comment]
If so, my suggestion is **you don't need to execute `map.clear()` before/after `map.remove()`.
Just execute `map.remove()`

**Comment by wf9a5m75** [comment]
ping

**Comment by bigbossmaher** [comment]
i have not used the map.remove() ever in my code .
i used the map.clear() only 2 times  in 2 diferent functions.
when i execture map.clear() 2 times can make this issue ?

**Comment by wf9a5m75** [comment]
You should use `map.clear()` only at once.

**Comment by bigbossmaher** [comment]
what is the command to remove the last marker

**Comment by wf9a5m75** [comment]
What do you mean? This plugin provides only `map.clear()` or `marker.remove()`

**Comment by bigbossmaher** [comment]
I want to use marker.remove() to delete the last marker , how can i make it
?

**Comment by wf9a5m75** [comment]
**You need to manage marker instances by yourself.**

For example,

```js
var _globalMarkerList = [];
...

map.addMarker({
   ...
}, function(marker) {
    _globalMarkerList.push(marker);
});


function removeLastMarker() {
   var lastMarker =  _globalMarkerList[_globalMarkerList.length - 1];
   if (lastMarker) {
      lastMarker.remove();
   }   
}
```

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update, I close this issue

**Comment by bigbossmaher** [comment]
thank you for your help.
i have a question
now i have markers in _globalMarkerList and in the default Variable ( i think it called  Markers )
how can i remove only markers that are in the default variable
