### ISSUE TITLE
Facing error while install plugin from "multiple_maps" branch

### ISSUE THREAD

**Issue by ypkkhatri** [mapsplugin/cordova-plugin-googlemaps#1578]
Hi,

I'm trying to update plugin for faster performance, but I'm getting error, below is the command I'm using: 
`
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="My_ORGINAL_KEY_FOR_ANDROID"
`

And Stack trace is:

```
× Running command - failed!
[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
[ERROR] An error occurred while running cordova plugin add
        https://github.com/mapsplugin/cordova-plugin-googlemaps#multi... (exit code 1):

        Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via
        registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
        npm WARN addRemoteGit  git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps resetting        remote
        C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0
        because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/mapsplugin/cordova-plugin-googlemaps.git
        C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0:
        Cloning into bare repository
        'C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0'...
        npm ERR! git clone --template=C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/mapsplugin/cordova-plugin-googlemaps.git
        C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0:
        fatal: Unable to find remote helper for 'https'
        npm ERR! Windows_NT 10.0.14393
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        "https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps" "--save"
        npm ERR! node v6.11.0
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/mapsplugin/cordova-plugin-googlemaps.git
        C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0
        npm ERR! Cloning into bare repository
        'C:\Users\Yougeshwar\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-mapsplugin-cordova-plugin-googlemaps-git-multiple-maps-19e06bb0'...
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     D:\FreelanceUpWork\arthur928\arthur-visualfusion\node_modules\npm-debug.log
```

Please help me

Thank you

**Comment by wf9a5m75** [comment]
Um, maybe `npm -g install npm`?

**Comment by ypkkhatri** [comment]
Yes its working now, after updating `npm`, but in new version it crashed my app, I'm closing this will create another issue for that

Thanks for help
