### ISSUE TITLE
Crash when using GroundOverlay

### ISSUE THREAD

**Issue by Tong2203** [mapsplugin/cordova-plugin-googlemaps#1721]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[x] feature request

**The plugin version:**  (check one with "x")
[x] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-googlemaps 2.0.6-beta-20170906-2336 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```

**Current behavior:**
I used `map.clear()` and `map.setDiv()` to remove all overlay.
Then, when add GroundOverlay next time, app leaks more memory and crashed.

Not necessarily in the second time. Maybe in third time or more.

I tested devices like:
Xperia z3 compact --- Android 4.4.4
Nexus 5 --- Android 6.0
Xperia XA --- Android 7.0

error log:

```
09-08 14:18:50.548 8934-9204/jp.com.dammyappli I/art: Forcing collection of SoftReferences for 64MB allocation
09-08 14:18:50.548 8934-9204/jp.com.dammyappli I/art: Starting a blocking GC Alloc
09-08 14:18:50.569 8934-9204/jp.com.dammyappli I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 9% free, 158MB/174MB, paused 590us total 20.060ms
09-08 14:18:50.570 8934-9204/jp.com.dammyappli W/art: Throwing OutOfMemoryError "Failed to allocate a 67108876 byte allocation with 16777216 free bytes and 33MB until OOM"
09-08 14:18:50.580 8934-9204/jp.com.dammyappli E/Surface: getSlotFromBufferLocked: unknown buffer: 0x930528f0
09-08 14:18:50.614 8934-9204/jp.com.dammyappli E/AndroidRuntime: FATAL EXCEPTION: GLThread 4838
                                                                 Process: jp.com.dammyappli, PID: 8934
                                                                 java.lang.OutOfMemoryError: Failed to allocate a 67108876 byte allocation with 16777216 free bytes and 33MB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.gl.k.a(:com.google.android.gms.DynamiteModulesB@11509438:7)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.gl.ah.a(:com.google.android.gms.DynamiteModulesB@11509438:73)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.gl.ah.a(:com.google.android.gms.DynamiteModulesB@11509438:33)
                                                                     at com.google.maps.api.android.lib6.impl.bk.a(:com.google.android.gms.DynamiteModulesB@11509438:60)
                                                                     at com.google.maps.api.android.lib6.gmm6.api.p.a(:com.google.android.gms.DynamiteModulesB@11509438:76)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.bs.a(:com.google.android.gms.DynamiteModulesB@11509438:626)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.bs.b(:com.google.android.gms.DynamiteModulesB@11509438:270)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.bb.f(:com.google.android.gms.DynamiteModulesB@11509438:257)
                                                                     at com.google.maps.api.android.lib6.gmm6.vector.bb.run(:com.google.android.gms.DynamiteModulesB@11509438:11)
09-08 14:18:50.749 8934-8934/jp.com.dammyappli W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
09-08 14:18:50.789 8934-9022/jp.com.dammyappli E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa8aec7a0
```

I put demo app on Bitbucket:

```
https://breezee_work@bitbucket.org/breezee_work/maptest.git
```

By the way,  is `groundOverlay.remove()` support callback function ?

Thanks a lot.

**Comment by wf9a5m75** [comment]
Thank you for sharing demo project. I will check it later.

**Comment by wf9a5m75** [comment]
修正しました。multiple_mapsブランチからプラグインをインストールしてください

![issue_1721_compress](https://user-images.githubusercontent.com/167831/30235760-553f95b4-94c1-11e7-855c-118efa3b33a6.gif)

**Comment by Tong2203** [comment]
迅速な対応、ありがとうございました。
検証したところ、大きく改善されましたが。
また、別の原因で落ちてしまいました。
Nexus 5 の場合は、およそ、起動後３分くらい、オーバレイ画像が白になって、落ちます。
エラーログは以下になります：
```
09-11 13:42:51.132 23530-23659/jp.com.dammyappli W/art: be4b5000-be4b5000 ---p 00000000 00:00 0 
09-11 13:42:51.132 23530-23659/jp.com.dammyappli W/art: be4b5000-becb4000 rw-p 00000000 00:00 0          [stack]
09-11 13:42:51.132 23530-23659/jp.com.dammyappli W/art: ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]
09-11 13:42:51.132 23530-23659/jp.com.dammyappli W/art: Large object allocation failed: Failed anonymous mmap(0x0, 67112960, 0x3, 0x2, 108, 0): Out of memory. See process maps in the log.
09-11 13:42:51.132 23530-23659/jp.com.dammyappli W/art: Throwing OutOfMemoryError "Failed to allocate a 67108876 byte allocation with 15341226 free bytes and 170MB until OOM"
09-11 13:42:51.132 23530-23537/jp.com.dammyappli W/art: Suspending all threads took: 44.134ms
09-11 13:42:51.624 23530-23659/jp.com.dammyappli W/Adreno-GSL: <sharedmem_gpumem_alloc_id:2207>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
09-11 13:42:51.636 23530-23659/jp.com.dammyappli E/Adreno-GSL: <gsl_memory_alloc_pure:1905>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
09-11 13:42:51.737 23530-23659/jp.com.dammyappli W/Adreno-GSL: <sharedmem_gpumem_alloc_id:2207>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
09-11 13:42:51.749 23530-23659/jp.com.dammyappli E/Adreno-GSL: <gsl_memory_alloc_pure:1905>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
09-11 13:42:51.749 23530-23659/jp.com.dammyappli W/Adreno-ES20: <core_glTexImage2D:501>: GL_OUT_OF_MEMORY
09-11 13:42:56.352 23530-23530/jp.com.dammyappli I/art: Starting a blocking GC NativeAlloc
09-11 13:42:56.352 23530-23530/jp.com.dammyappli I/art: Starting a blocking GC NativeAlloc
09-11 13:42:56.423 23530-23530/jp.com.dammyappli D/AndroidRuntime: Shutting down VM
09-11 13:42:56.485 23530-23530/jp.com.dammyappli E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: jp.com.dammyappli, PID: 23530
                                                                   java.lang.RuntimeException: Could not copy bitmap to parcel blob.
                                                                       at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
                                                                       at android.graphics.Bitmap.writeToParcel(Bitmap.java:1541)
                                                                       at bsb.a(:com.google.android.gms@11509438:7)
                                                                       at wpm.a(:com.google.android.gms@11509438:16)
                                                                       at wju.a(:com.google.android.gms@11509438:2)
                                                                       at wjw.a(:com.google.android.gms@11509438:5)
                                                                       at wpl.a(:com.google.android.gms@11509438:15)
                                                                       at wpl.onTransact(:com.google.android.gms@11509438:8)
                                                                       at android.os.Binder.transact(Binder.java:387)
                                                                       at com.google.android.gms.internal.zzed.zza(Unknown Source)
                                                                       at com.google.android.gms.maps.model.internal.zzc.zzd(Unknown Source)
                                                                       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
                                                                       at plugin.google.maps.PluginGroundOverlay$7.onPostExecute(PluginGroundOverlay.java:388)
                                                                       at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:522)
                                                                       at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:31)
                                                                       at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
試験動画はこちら：
https://youtu.be/CcHca7zqHzM

**Comment by Tong2203** [comment]
すみません。
もう一つ質問がありました。

前回のバージョンでは、端末の戻るボタンが封印されましたが、
最新版では、復活したみたいです。

これば機能の変更でしょうか？
もう一度戻るボタンを封印する方法を教えていただけませんか？

どうぞ、よろしくお願いいたします。

**Comment by wf9a5m75** [comment]
CordovaはJavaとJavaScriptの両方を使う関係上、インスタンスを作成、削除しても完全にはメモリからクリアできません。なので今の使用方法はこのプラグインには向いていません。
TileOverlayを使うか、ネイティブでコード書いてもらううのがいいと思います。

バックボタンは使えないほうがバグです。
ただしCoedovaではバックボタンに対するフック関数を登録することができます。
空のフック関数を登録してもらえばいいと思います。

**Comment by Tong2203** [comment]
わかりました。
いつもありがとうございます。

**Comment by Tong2203** [comment]
たびたびすみません。
2.0.7-beta-20170912-1635にアップデートして、検証したところ。
クラッシュが再発しました。

```
09-13 17:07:20.309 5537-5537/jp.com.dammyappli W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415f0d88)
09-13 17:07:20.309 5537-5537/jp.com.dammyappli E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: jp.com.dammyappli, PID: 5537
                                                                 java.lang.OutOfMemoryError
                                                                     at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
                                                                     at android.graphics.Bitmap.access$000(Bitmap.java:29)
                                                                     at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1459)
                                                                     at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1451)
                                                                     at gs.a(:com.google.android.gms.DynamiteModulesB@11509036:7)
                                                                     at com.google.android.gms.maps.model.internal.b.onTransact(:com.google.android.gms.DynamiteModulesB@11509036:31)
                                                                     at android.os.Binder.transact(Binder.java:361)
                                                                     at bsd.a(:com.google.android.gms@11509036:2)
                                                                     at toi.a(:com.google.android.gms@11509036:16)
                                                                     at tiq.a(:com.google.android.gms@11509036:2)
                                                                     at tis.a(:com.google.android.gms@11509036:5)
                                                                     at toh.a(:com.google.android.gms@11509036:15)
                                                                     at toh.onTransact(:com.google.android.gms@11509036:8)
                                                                     at android.os.Binder.transact(Binder.java:361)
                                                                     at com.google.android.gms.internal.zzed.zza(Unknown Source)
                                                                     at com.google.android.gms.maps.model.internal.zzc.zzd(Unknown Source)
                                                                     at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
                                                                     at plugin.google.maps.PluginGroundOverlay$7.onPostExecute(PluginGroundOverlay.java:388)
                                                                     at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:522)
                                                                     at plugin.google.maps.AsyncLoadImage.onPostExecute(AsyncLoadImage.java:31)
                                                                     at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                     at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:212)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```
ご確認をいただけませんか？
よろしくお願いいたします。

**Comment by wf9a5m75** [comment]
クラッシュするバグを修正して、メモリリークを改善しました。
multiple_mapsブランチから再インストールしてください。

**Comment by Tong2203** [comment]
３０分かけて試験しました。
問題がありませでした。
ありがとうございました。
