### ISSUE TITLE
Google Maps Plugin is not compatible with cordova-plugin-camera-preview (again)

### ISSUE THREAD

**Issue by battika** [mapsplugin/cordova-plugin-googlemaps#2003]
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.1.2-beta-20180117-0015 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
    "@ionic-native/camera-preview": "^4.3.0",
    "@ionic-native/core": "4.5.2",
    "@ionic-native/google-maps": "^4.5.2",
    "@ionic-native/splash-screen": "4.5.2",
    "@ionic-native/status-bar": "4.5.2",
```

**Current behavior:**
When using your sample app, latest Google Maps plugin version with current stable version of cordova-plugin-camera-preview when startCamera() is called, application crashes on Android. If map is removed using the remove() method beforehand everything works OK.

**Expected behavior:**
Map and camera should be able to work co-residently.

**Related code, data or error log (please format your code or data):**
Your sample code is located here:

https://github.com/wf9a5m75/camerapreview-vs-maps

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1784

**Comment by wf9a5m75** [comment]
Please provide the crash logs.

**Comment by wf9a5m75** [comment]
It seems the camera preview plugin problem. not this plugin.

```
01-17 11:45:25.571 31313-31495/io.ionic.starter W/zygote64: Skipping duplicate class check due to unsupported classloader
01-17 11:45:26.451 31313-31431/io.ionic.starter D/CameraPreview: start camera action
01-17 11:45:26.453 31313-31313/io.ionic.starter D/AndroidRuntime: Shutting down VM
01-17 11:45:26.454 31313-31313/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: io.ionic.starter, PID: 31313
                                                                  java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
                                                                      at com.cordovaplugincamerapreview.CameraPreview$1.run(CameraPreview.java:241)
                                                                      at android.os.Handler.handleCallback(Handler.java:790)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
