### ISSUE TITLE
Error while install in iOS

### ISSUE THREAD

**Issue by bhumin3i** [mapsplugin/cordova-plugin-googlemaps#2034]
```
$ cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=xxxxxxx --variable API_KEY_FOR_IOS=xxxxxxx --save 


Failed to install 'cordova-plugin-googlemaps': CordovaError: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf
npm ERR! /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rac/.npm/_logs/2018-01-30T11_16_56_024Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)

(node:2863) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf
npm ERR! /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rac/.npm/_logs/2018-01-30T11_16_56_024Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:2863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bhumin3i** [comment]
I notice  this issue coming after add 
$ionic cordova plugin add phonegap-plugin-push

**Comment by wf9a5m75** [comment]
Ask to the phonegap-plugin-push developer.

**Comment by wf9a5m75** [comment]
Regarding of the error log, it seems the npm fails to `git clone` because of permission problem.

```
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf
npm ERR! /Users/rac/.npm/_cacache/tmp/git-clone-cf9334cf/.git: Permission denied
```

So please try these steps:

```
$> npm -g install npm

$> brew upgrade git  // or install the latest git command from https://git-scm.com/downloads

$> ionic cordova platform rm ios

$> ionic cordova platform add ios
```

Even the above steps do not work, you can install from local.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

$> cd (your project dir)

$> ionic cordova plugin add (path to)/cordova-plugin-googlemaps-sdk
```

**Comment by wf9a5m75** [comment]
ping

**Comment by bhandaribhumin** [comment]
thanks @wf9a5m75  let me check

**Comment by bhandaribhumin** [comment]
thanks @wf9a5m75 it's work but still I'm confuse my config.xml look like 
------->

<plugin name="com.googlemaps.ios" spec="/Users/bhuminb/Desktop/Projects/google/cordova-plugin-googlemaps-sdk" />
    <plugin name="cordova-plugin-googlemaps" spec="^2.2.2">
        <variable name="API_KEY_FOR_ANDROID" value="xxxgxxxxxx" />
        <variable name="API_KEY_FOR_IOS" value="xxxxxxxxx" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Show your location on the map" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Trace your location on the map" />
    </plugin>

**Comment by wf9a5m75** [comment]
Please ask to the ionic team about the building error of ionic-native.

**Comment by garycsebastian** [comment]
Failed to install 'cordova-plugin-googlemaps': CordovaError: Failed to fetch plugin
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init
 --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

**Comment by wf9a5m75** [comment]
No, it is your git command and npm problem, not plugin's problem.
Please update npm command.

**Comment by garycsebastian** [comment]
I started a new proyect and no problem to install... thanks

**Comment by leo4444** [comment]
I had the same problem ...
I already had a project on Android developed on Windows 10 and I was now working on Mac for iOS. When I wanted to add the platform (sudo ionic cordova platform add ios) I had this problem ... I tried many things but the problem was that I added "sudo" in the command line. Removing "sudo" gave me permission errors in the platforms / ios directory, so I gave it read / write permissions and ran the command again ...
This was what worked for me, I hope it serves the one who has this problem
