### ISSUE TITLE
Crash due to permissions

### ISSUE THREAD

**Issue by dlorenzo** [mapsplugin/cordova-plugin-googlemaps#2136]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.2.2 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**`
```
"@ionic-native/core": "4.4.0",
"@ionic-native/google-maps": "^4.5.3",
```

```
"PLAY_SERVICES_VERSION": "11.8.0",
"ANDROID_SUPPORT_V4_VERSION": "27.1.0"
```

**Current behavior:**
When requesting user location, permission is asked but crashes immediately after it's given:

```
ava.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompatApi23$RequestPermissionsRequestCodeValidator;
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at plugin.google.maps.PluginLocationService.getMyLocation(PluginLocationService.java:226)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at plugin.google.maps.PluginLocationService$1.run(PluginLocationService.java:72)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.ActivityCompatApi23$RequestPermissionsRequestCodeValidator" on path: DexPathList[[zip file "/data/app/xxx-ohdEoLwP1tXpoPNo0WIfuA==/base.apk"],nativeLibraryDirectories=[/data/app/xxx-ohdEoLwP1tXpoPNo0WIfuA==/lib/x86, /data/app/xxx-ohdEoLwP1tXpoPNo0WIfuA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-13 12:44:45.060 31256 31256 E AndroidRuntime: 	... 7 more
```

**Expected behavior:**
Get user location and place it in the map.

**EDIT:
Seems to be working fine after upgrading cordova-android to v7.1.0 (was 7.0.0 before) and settings minSdk to 19.**

**Comment by wf9a5m75** [comment]
This plugin supports minimum Android sdk version is 19. No longer supported less than 19.
