### ISSUE TITLE
problem in android

### ISSUE THREAD

**Issue by hackeo1** [mapsplugin/cordova-plugin-googlemaps#2175]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-google-app-conversion-tracker 0.0.2 "GoogleAppTracking"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-intercom 5.0.2 "Intercom"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-threatmetrix 1.0.0 "ThreatMetrix"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
app crashes

**Expected behavior:**
app not crashing

**Related code, data or error log (please format your code or data):**

When I init the app in android I get a crash problem 

This is my system info
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.4.0 ios 4.5.4
    Ionic Framework   : ionic1 1.3.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
```

This is the logcat error
```
03-22 11:50:17.581 16475 16475 E AndroidRuntime: FATAL EXCEPTION: main
03-22 11:50:17.581 16475 16475 E AndroidRuntime: Process: com.vianex.mobile.app, PID: 16475
03-22 11:50:17.581 16475 16475 E AndroidRuntime: java.lang.NoSuchMethodError: No static method checkNotNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbq; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbq' appears in /data/app/com.vianex.mobile.app-ex-bTz2O27zkeahrY4QGog==/base.apk)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source:7)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:208)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:6179)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:72)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at com.vianex.mobile.app.MainActivity.onCreate(MainActivity.java:39)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7002)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6548)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-22 11:50:17.581 16475 16475 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by wf9a5m75** [comment]
Duplicate with https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2175
