### ISSUE TITLE
xml2js error even in v2.2.9

### ISSUE THREAD

**Issue by caiotarifa** [mapsplugin/cordova-plugin-googlemaps#2182]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
---

I noted that in the last changelog (v2.2.9) there was a bug fix involving the xml2js library. But when I tested here, the problem persists.

![gmaps](https://user-images.githubusercontent.com/197979/37945689-c410f4dc-3157-11e8-802a-e8abdceb7b98.png)

```
$ cordova plugin rm cordova-plugin-googlemaps
(node:68929) UnhandledPromiseRejectionWarning: Error: Cannot find module '/path/to/plugins/cordova-plugin-googlemaps/node_modules/xml2js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at module.exports (/path/to/plugins/cordova-plugin-googlemaps/src/before_plugin_rm.js:16:16)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:68929) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68929) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wf9a5m75** [comment]
Please share the project files , and indicates how to reproduce the issues 100%.

**Comment by caiotarifa** [comment]
@wf9a5m75, I am sorry, I forgot the steps.

I am using this template:
https://github.com/caiobiodere/cordova-template-framework7-vue-webpack

It is simple to reproduce:

1. `$ cordova create my-app com.example.app MyApp --template cordova-template-framework7-vue-webpack`
2. `$ cd my-app/`
3. `npm install`
4. `$ cordova platform add browser ios`
5. `$ cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="...-xVWDKkBuJ1O3s8" --variable API_KEY_FOR_IOS="..."`

**Comment by wf9a5m75** [comment]
```
$> cordova create my-app com.example.app MyApp --template https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
Creating a new cordova project.

$> cd /my-app/

$> my-app masashi$ ls
config.xml		plugins			webpack.config.js
hooks			res			www
package.json		src
platforms		webpack

$> npm install

> fsevents@1.1.3 install /Users/masashi/Documents/workspace/test/my-app/node_modules/fsevents
> node install

[fsevents] Success: "/Users/masashi/Documents/workspace/test/my-app/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> node-sass@4.8.3 install /Users/masashi/Documents/workspace/test/my-app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/darwin-x64-51_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/masashi/Documents/workspace/test/my-app/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Caching binary to /Users/masashi/.npm/node-sass/4.8.3/darwin-x64-51_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/masashi/Documents/workspace/test/my-app/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.8.3 postinstall /Users/masashi/Documents/workspace/test/my-app/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/masashi/Documents/workspace/test/my-app/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN com.example.app@1.0.0 No repository field.

added 1197 packages from 724 contributors in 136.877s

$> cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.example.app
	Name: MyApp
iOS project created with cordova-ios@4.5.4
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Cordova hook completed. Resuming to run your cordova command...
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...

$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml

$> cd plugins/

$> ls
com.googlemaps.ios		fetch.json
cordova-plugin-googlemaps	ios.json
cordova-plugin-whitelist

$> cd cordova-plugin-googlemaps/

$> ls
CONTRIBUTING.md		node_modules		src
LICENSE			package.json		www
README.md		plugin.xml
images			plugin.xml.original

$> cd ../../

$> cordova plugin rm cordova-plugin-googlemaps
Uninstalling 1 dependent plugins.
Uninstalling com.googlemaps.ios from ios
Uninstalling cordova-plugin-googlemaps from ios
Removing "cordova-plugin-googlemaps"
Removing plugin cordova-plugin-googlemaps from config.xml file...
Removing cordova-plugin-googlemaps from package.json

$> 
```

**Comment by caiotarifa** [comment]
I saw that you installed only the "ios" platform and not the "browser" as I described. Is this difference causing the problem?

```
cordova platform add browser ios
```

**Comment by wf9a5m75** [comment]
This plugin does not support browser

**Comment by caiotarifa** [comment]
Yes, I know.

In the browser version I intend to use the JavaScript API. I just need to make a condition in the code.

But add "browser" as a platform can't be an impediment to using this library.

**Comment by wf9a5m75** [comment]
```

$> cordova create my-app com.example.app MyApp --template https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
Creating a new cordova project.

$> cd my-app/

$> cordova platform add browser ios
Using cordova-fetch for cordova-browser@~5.0.1
Adding browser project...
Creating Cordova project for cordova-browser:
	Path: /Users/masashi/Documents/workspace2/test/my-app/platforms/browser
	Name: MyApp
Before deploy hook started...
Checking is node modules installed...
Node modules not found. Installing...
Node modules installed successfully!
Cordova hook completed. Resuming to run your cordova command...
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for browser
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving browser@~5.0.3 into config.xml file ...
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.example.app
	Name: MyApp
iOS project created with cordova-ios@4.5.4
Installing "cordova-plugin-whitelist" for ios
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Cordova hook completed. Resuming to run your cordova command...
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...

$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
Installing "cordova-plugin-googlemaps" for browser
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml

$> cordova plugin rm cordova-plugin-googlemaps
Uninstalling cordova-plugin-googlemaps from browser
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/BaseClass.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/BaseArrayClass.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/LatLng.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/LatLngBounds.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/VisibleRegion.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Location.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/CameraPosition.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Polyline.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Polygon.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Marker.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/HtmlInfoWindow.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Circle.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/TileOverlay.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/GroundOverlay.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Common.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/encoding.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/spherical.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/poly.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Geocoder.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/LocationService.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Map.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/event.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/MapTypeId.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/KmlOverlay.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/KmlLoader.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Environment.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/MarkerCluster.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/Cluster.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/geomodel.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/commandQueueExecutor.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/pluginInit.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/CordovaGoogleMaps.js
js-module uninstall called : plugins/cordova-plugin-googlemaps/www/StreetView.js
Uninstalling 1 dependent plugins.
Uninstalling com.googlemaps.ios from ios
Uninstalling cordova-plugin-googlemaps from ios
Removing "cordova-plugin-googlemaps"
Removing plugin cordova-plugin-googlemaps from config.xml file...
Removing cordova-plugin-googlemaps from package.json

$>  cordova -v
8.0.0

$>  node -v
v9.3.0

$> cordova platform list
Installed platforms:
  browser 5.0.3
  ios 4.5.4
Available platforms: 
  android ~7.0.0
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

```

**Comment by caiotarifa** [comment]
Unfortunately I don't know what may be happening, is it something related to my environment?

What information other information could I provide?

I recorded a video with the whole process. https://streamable.com/qvrvr

**Comment by wf9a5m75** [comment]
Could you share the all files including `node_modules` of the `my-app` project on to Github?

**Comment by caiotarifa** [comment]
Sure! https://github.com/caiotarifa/my-app

**Comment by wf9a5m75** [comment]
Thank you for sharing. Um, it seems `npm` version might affect?

**Comment by wf9a5m75** [comment]
Okay, please try again with `multiple_maps` branch version.

```
$ cordova create my-app com.example.app MyApp --template cordova-template-framework7-vue-webpack
$ cd my-app/
$ npm install
$ cordova platform add browser ios
$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

**Comment by caiotarifa** [comment]
unfortunately the problem persists

![captura de tela 2018-03-27 as 16 13 32](https://user-images.githubusercontent.com/197979/37989485-e9e0bf76-31d9-11e8-8206-31884821945b.png)

**Comment by caiotarifa** [comment]
Awesome, @wf9a5m75. Now works...

```
$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#73ec7f7a  --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
Installing "cordova-plugin-googlemaps" for browser
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
```

**Comment by wf9a5m75** [comment]
Sounds good :)
