### ISSUE TITLE
Map not showing up when firebase plugin is installed

### ISSUE THREAD

**Issue by mahnuh** [mapsplugin/cordova-plugin-googlemaps#2203]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.5.3 "SafariViewController"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
`@ionic-native/core`: "4.6.0",
`@ionic-native/google-maps`: "^4.5.3",

**Current behavior:**
Google Map won't show up when cordova-plugin-firebase is installed. Using cordova-android@7.1.0, same goes for 7.0.0. On 6.4.0 app crashes when both plugins are installed.

**Expected behavior:**
Map would work

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by mahnuh** [comment]
@wf9a5m75 I just added you as a collaborator!

**Comment by wf9a5m75** [comment]
Thank you for sharing your project, but I can't understand what you want to see me.
The project does not have map page.

**Comment by mahnuh** [comment]
@wf9a5m75 My bad, looks like I did forget to push the changes. Should be available now. I also added some more details to the README.md.

**Comment by mahnuh** [comment]
@wf9a5m75 Now the app just crashes when starting. I get the following error:

````
04-09 15:32:55.667 12762 12762 E AndroidRuntime: FATAL EXCEPTION: main
04-09 15:32:55.667 12762 12762 E AndroidRuntime: Process: de.mahnuh.BergApp, PID: 12762
04-09 15:32:55.667 12762 12762 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zza(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbq; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbq' appears in /data/app/de.mahnuh.BergApp-NaryLb-UjsO2WqyrV1-Gjg==/base.apk)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source:7)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:209)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:6272)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:72)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at de.mahnuh.BergApp.MainActivity.onCreate(MainActivity.java:39)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7174)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
04-09 15:32:55.667 12762 12762 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
````

**Comment by wf9a5m75** [comment]
The error says your specified version of the Google Play Services SDK is too old.
You need to specify 12.0.1

**Comment by mahnuh** [comment]
Ok, that prevents the app from crashing, the map will still not show...

**Comment by wf9a5m75** [comment]
Please show me the screenshot

**Comment by mahnuh** [comment]
I might be on to something and will get back to you shortly. Maybe I figured it out.

**Comment by mahnuh** [comment]
Sorry for letting you wait. The problem actually was, that the google maps plugin was missing. This was because the firebase plugin broke the google maps plugin installation process which I did not notice before. After fixing this issue everything works like charm now.

The hint with the Google Play Services version 12.0.1 helped me a lot, thanks!
