### ISSUE TITLE
Incompatibility with the "phonegap-plugin-push" plugin.

### ISSUE THREAD

**Issue by caiotarifa** [mapsplugin/cordova-plugin-googlemaps#2212]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [ ] **iOS**

**cordova information:**

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.3.0-beta-20180327-1257 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.2.2 "PushPlugin"
```

I am using the 2.3.0-beta because the #2192 issue. _I can share a GitHub repo, but just follow these steps to reproduce:_

``` bash
$ cordova create my-app com.example.app MyApp --template cordova-template-framework7-vue-webpack
$ cd my-app/
$ npm install
$ cordova platform add ios android
$ cordova plugin add phonegap-plugin-push
$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

[It may be useful to read this wiki.](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md)

**Current behavior:**

My problem is similar to #2159. Without the `cordova-plugin-googlemaps` my build works.

**Related code, data or error log (please format your code or data):**

The versions:

``` bash
$ cordova -v
8.0.0

$ node -v
v9.5.0

$ npm -v
5.6.0
```

The error:

``` bash
$ cordova run android

...
Found com.google.android.gms:play-services-maps:12.0.0, but version 11.6.2 is needed for the google-services plugin.
Found com.google.android.gms:play-services-location:12.0.0, but version 11.6.2 is needed for the google-services plugin.
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
21 actionable tasks: 1 executed, 20 up-to-date
(node:4142) UnhandledPromiseRejectionWarning: Error: /Users/user/Sites/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
    at ChildProcess.whenDone (/Users/user/Sites/app/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:4142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My `config.xml`:

``` xml
<plugin name="phonegap-plugin-push" spec="^2.2.2">
    <variable name="SENDER_ID" value="..." />
    <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
    <variable name="FCM_VERSION" value="11.6.2" />
</plugin>
<plugin name="cordova-plugin-googlemaps" spec="https://github.com/mapsplugin/cordova-plugin-googlemaps.git#73ec7f7a">
    <variable name="API_KEY_FOR_ANDROID" value="..." />
    <variable name="API_KEY_FOR_IOS" value="..." />
    <variable name="PLAY_SERVICES_VERSION" value="11.6.2" />
    <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
    <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="This app wants to get your location while this app runs only." />
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="This app wants to get your location always, even this app runs in background." />
</plugin>
```

**Comment by wf9a5m75** [comment]
The error log obviously says 
```
Found com.google.android.gms:play-services-maps:12.0.0, but version 11.6.2 is needed for the google-services plugin.
Found com.google.android.gms:play-services-location:12.0.0, but version 11.6.2 is needed for the google-services plugin.
```

The version `11.6.2` is too much old.

**Comment by caiotarifa** [comment]
Yes, `phonegap-push-plugin` required the `11.6.21` version of Google Play Services, and I was edited my `config.xml` with this version:

``` xml
<plugin name="cordova-plugin-googlemaps">
    ...
    <variable name="PLAY_SERVICES_VERSION" value="11.6.2"/>
    ...
</plugin>
```

But after I reinstalled it, it still downloading the Google Play Services version 12. 🤔 

So I noted that this configuration exists in `package.json` too,  I changed and reinstalled the plugin and now my app is build. 🎉 

``` json
"cordova-plugin-googlemaps": {
    ...
    "PLAY_SERVICES_VERSION": "11.6.2",
    ...
}
```
