### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined on this.map.getMyLocation()

### ISSUE THREAD

**Issue by macklus** [mapsplugin/cordova-plugin-googlemaps#2218]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.7.0",
```

**Current behavior:**
When i try to execute **this.map.getMyLocation()** function, it hangs with error:
```
[INFO:CONSOLE(1)] "Error: Uncaught (in promise): TypeError: Cannot read property 'bind' of undefined
04-15 19:19:42.332 20460 20460 I chromium: TypeError: Cannot read property 'bind' of undefined
04-15 19:19:42.332 20460 20460 I chromium:     at Map.getMyLocation (file:///android_asset/www/plugins/cordova-plugin-googlemaps/www/Map.js:298:104)
04-15 19:19:42.332 20460 20460 I chromium:     at a (file:///android_asset/www/build/vendor.js:1:451277)
04-15 19:19:42.332 20460 20460 I chromium:     at file:///android_asset/www/build/vendor.js:1:452865
04-15 19:19:42.332 20460 20460 I chromium:     at file:///android_asset/www/build/vendor.js:1:455073
04-15 19:19:42.332 20460 20460 I chromium:     at new t (file:///android_asset/www/build/polyfills.js:3:21506)
04-15 19:19:42.332 20460 20460 I chromium:     at file:///android_asset/www/build/vendor.js:1:455047
04-15 19:19:42.332 20460 20460 I chromium:     at O (file:///android_asset/www/build/vendor.js:1:455284)
04-15 19:19:42.332 20460 20460 I chromium:     at e.<anonymous> (file:///android_asset/www/build/vendor.js:1:452661)
04-15 19:19:42.332 20460 20460 I chromium:     at e.value [as getMyLocation] (file:///android_asset/www/build/vendor.js:1:454316)
04-15 19:19:42.332 20460 20460 I chromium:     at file:///android_asset/www/build/main.js:1:10294", source: file:///android_asset/www/build/main.js (1)
```

**Expected behavior:**
It should show location permission windows

**Related code, data or error log (please format your code or data):**

You can see example code on branch **maps** of https://github.com/macklus/ionic-3-examples

**Comment by wf9a5m75** [comment]
Use `LocationService.getMyLocation()` or reinstall from the multiple_maps branch please

**Comment by macklus** [comment]
You are right.
I suppoused multiple_branchs was stable release, but it is not.

thanks!

**Comment by kozuch** [comment]
@wf9a5m75 

you meant plugin.google.maps.LocationService.getMyLocation()
