### ISSUE TITLE
Install fails trying to fetch cordova-plugin-googlemaps-sdk 2.7.0 

### ISSUE THREAD

**Issue by maximilianloy** [mapsplugin/cordova-plugin-googlemaps#2271]
First of all thanks for this great plugin! I have used the old version before, but when trying to add the latest version of the plugin I get an error during install.

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
npm@6.0.1
node@v8.1.4

cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-googlemaps 2.3.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic 4.1.7 "IonicCordova"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-safariviewcontroller 1.5.3 "SafariViewController"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    
"ionic-native/core": "4.7.0"
"ionic-native/google-maps": "^4.8.2"

**Current behavior:**
```
$ ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
> cordova plugin add cordova-plugin-googlemaps@2.3.0 --variable API_KEY_FOR_ANDROID=... --variable API_KEY_FOR_IOS=... --save
Installing "cordova-plugin-googlemaps" for ios

Failed to install 'cordova-plugin-googlemaps': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

(node:4422) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.7.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout 2.7.0
npm ERR! error: pathspec '2.7.0' did not match any file(s) known to git.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/max/.npm/_logs/2018-05-17T10_41_14_737Z-debug.log
(node:4422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Tried several times and other plugins can be installed, so it is definitely not a connection problem

**Comment by wf9a5m75** [comment]
Sorry, git tag does not attach well.
I attached `2.7.0`. Please try again.
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/tree/2.7.0

**Comment by maximilianloy** [comment]
Now its working, thanks

**Comment by mikilion** [comment]
I experience same issue yet
