### ISSUE TITLE
error after map.clear() when i add marker again

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#2325]
on my project i have some markers, when i clear may map with `map.clear()` i get this error 

```
6-22 17:19:30.462 24549-24549/com.nrg.iSchool E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.nrg.iSchool, PID: 24549
                                                                 java.lang.IllegalArgumentException: Unmanaged descriptor
                                                                     at com.google.maps.api.android.lib6.common.n.d(:com.google.android.gms.dynamite_dynamitemodulesb@12685006@12.6.85 (020300-197041431):32)
                                                                     at com.google.maps.api.android.lib6.impl.o.c(:com.google.android.gms.dynamite_dynamitemodulesb@12685006@12.6.85 (020300-197041431):17)
                                                                     at com.google.maps.api.android.lib6.impl.cy.a(:com.google.android.gms.dynamite_dynamitemodulesb@12685006@12.6.85 (020300-197041431):181)
                                                                     at com.google.android.gms.maps.model.internal.q.onTransact(:com.google.android.gms.dynamite_dynamitemodulesb@12685006@12.6.85 (020300-197041431):87)
                                                                     at android.os.Binder.transact(Binder.java:380)
                                                                     at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source)
                                                                     at com.google.android.gms.internal.maps.zzv.zzg(Unknown Source)
                                                                     at com.google.android.gms.maps.model.Marker.setIcon(Unknown Source)
                                                                     at plugin.google.maps.PluginMarker$3.run(PluginMarker.java:156)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5974)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

**Comment by wf9a5m75** [comment]
Please share your project files on github.

You can NOT reuse the marker instance that is removed from map at once.

**Comment by dsemerida** [comment]
is correct use allways `map.clear()` when we have clear all components on the mark? or is more simple declare every component with his own variable and clear this variable or use `control.remove()` ?

**Comment by wf9a5m75** [comment]
`map.clear()` removes all overlays safely. 

I guess you tried executing `map.clear()` or `map.remove()` during `map.clear()` something.

If you can't solve the problem by yourself, please share your project files on github. Otherwise, please debug by yourself.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.

**Comment by benoffi7** [comment]
Try

```
    mClusterManager.markerCollection.clear();
    mMap.clear()
```
