### ISSUE TITLE
Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference

### ISSUE THREAD

**Issue by spacesuitdiver** [mapsplugin/cordova-plugin-googlemaps#2381]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.mbppower.camerapreview 0.0.8 "cordova-plugin-camera-preview"
com.phonegap.plugins.facebookconnect 1.7.1.3 "Facebook"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-launch-review 3.1.0 "Launch Review"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-appavailability 0.4.1 "AppAvailability"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-cszbar 1.3.2 "ZBar barcode scanner"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-disable-bitcode 1.3.2 "DisableBitcode"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-intercom 4.1.2 "Intercom"
cordova-plugin-localization-strings 1.1.1 "Localization"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-okhttp 2.0.0 "OkHttp"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"
```

**Current behavior:**
On occasion I end up with the error below on Android and the app crashes. This happens on version 2.3.6, attempting to upgrade now. Still trying to pinpoint what might be the cause, it happens sporadically. 

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mycorp.myapp.test, PID: 3685
                  java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
                      at plugin.google.maps.MyPluginLayout$1.run(MyPluginLayout.java:118)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I can't debug without your project files

**Comment by spacesuitdiver** [comment]
@wf9a5m75 I'll see if I can make a new project that has the same issue, in the meantime any thoughts on the error? I'm wondering if it's because we use dynamic height/width. 

Here's at least the targeted div in question:

```
        <div id="map-canvas"
            style="height: 100%; width: 100%;"
            ng-transclude
        ></div>
```

**Comment by wf9a5m75** [comment]
I have no idea.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread. If you have any updates, you can still update here.
