### ISSUE TITLE
2 errors during compilation: local variable <xxx> is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by yosigolan** [mapsplugin/cordova-plugin-googlemaps#2386]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.0.5 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.0.2 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-photo-library 2.1.1 "Photo Library"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 4.9.0
@ionic-native/google-maps : 4.8.2
```

**Current behavior:**
during build i get these errors:
```
C:\GitRepos\SeeVoovMobileApp\platforms\android\src\plugin\google\maps\PluginGroundOverlay.java:438: error: local variable imageOptions is accessed from within inner class; needs to be declared final
        AsyncLoadImage task = new AsyncLoadImage(cordova, webView, imageOptions, onComplete);
                                                                   ^
C:\GitRepos\SeeVoovMobileApp\platforms\android\src\plugin\google\maps\PluginGroundOverlay.java:438: error: local variable onComplete is accessed from within inner class; needs to be declared final
        AsyncLoadImage task = new AsyncLoadImage(cordova, webView, imageOptions, onComplete);
```

it happens in 2.3.10 but not in 2.3.6

**Expected behavior:**
build should pass

**Comment by yosigolan** [comment]
When i try to use the multiple_maps branch as you suggested using this commnad:
```cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps``` i recive this error:
```(node:7816) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SeeVoov-Developer\AppData\Roaming\npm-cache\_logs\2018-08-12T08_23_21_085Z-debug.log
    at C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:7816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reject```

**Comment by wf9a5m75** [comment]
I can't take care of your git problem too. That's your environment problem. If you are not familiar with git, use GitHub git client tool, then please install the plugin from local.
