### ISSUE TITLE
Cannot find symbol TBXML

### ISSUE THREAD

**Issue by clzola** [mapsplugin/cordova-plugin-googlemaps#2390]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
com.lampa.startapp 0.1.4 "startApp"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^4.11.0
@ionic-native/google-maps : ^4.9.1
```

**Current behavior:**
I cannot build for Android using command `ionic cordova build android`.
Here is the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.642 secs
(node:6449) UnhandledPromiseRejectionWarning: Error: /home/clzola/Workspace/Ionic/CityBeep/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/clzola/Workspace/Ionic/CityBeep/platforms/android/src/plugin/google/maps/PluginKmlOverlay.java:20: error: package za.co.twyst.tbxml does not exist
import za.co.twyst.tbxml.TBXML;
                        ^
/home/clzola/Workspace/Ionic/CityBeep/platforms/android/src/plugin/google/maps/PluginKmlOverlay.java:151: error: cannot find symbol
    private Bundle parseXml(TBXML tbxml, long rootElement) {
                            ^
  symbol:   class TBXML
  location: class PluginKmlOverlay.KmlParserClass
/home/clzola/Workspace/Ionic/CityBeep/platforms/android/src/plugin/google/maps/PluginKmlOverlay.java:124: error: cannot find symbol
      TBXML tbxml = new TBXML();
      ^
  symbol:   class TBXML
  location: class PluginKmlOverlay
/home/clzola/Workspace/Ionic/CityBeep/platforms/android/src/plugin/google/maps/PluginKmlOverlay.java:124: error: cannot find symbol
      TBXML tbxml = new TBXML();
                        ^
  symbol:   class TBXML
  location: class PluginKmlOverlay
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/home/clzola/Workspace/Ionic/CityBeep/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:6449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Expected behavior:**
Build succeeds.

I have this project.properties file:

```
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-auth:15.0.+
cordova.system.library.2=com.google.android.gms:play-services-identity:15.0.+
cordova.system.library.4=com.android.support:support-v4:26.+
cordova.system.library.5=com.android.support:support-v13:26.+
cordova.system.library.6=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.7=com.google.firebase:firebase-messaging:15.0.+
cordova.system.library.8=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.9=com.google.android.gms:play-services-maps:15.0.+
cordova.system.library.10=com.google.android.gms:play-services-location:15.0.+

cordova.gradle.include.1=cordova-plugin-badge/app-badge.gradle
cordova.gradle.include.2=cordova-plugin-local-notification/app-localnotification.gradle
cordova.gradle.include.3=phonegap-plugin-push/app-push.gradle
```

**Comment by wf9a5m75** [comment]
Please create a repository, then share your project files, including the platforms directly, www directly, config.xml, src directory, package.json, and any other files, on to GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by clzola** [comment]
You can close this, I manged to solve it, I was missing cordova.gradle.include.4 pointint to that library which was missing :D
