### ISSUE TITLE
Application crashes when using cordova-plugin-googlemaps with onesignal-cordova-plugin

### ISSUE THREAD

**Issue by spinninghamster** [mapsplugin/cordova-plugin-googlemaps#2398]
**I'm submitting a ...**  (check one with "x")
- [x ] any problem or bug report

**OS:**  (check one with "x")
- [x ] **Android**

**cordova information:** 

(I am using PhoneGap Build)

```
<gap:plugin name="cordova-plugin-whitelist" source="npm" />
<gap:plugin name="cordova-plugin-statusbar" source="npm" />
<gap:plugin name="cordova-plugin-device" source="npm" />		
<gap:plugin name="cordova-plugin-inappbrowser" source="npm" />		
<gap:plugin name="cordova-plugin-splashscreen" source="npm" />	
<gap:plugin name="cordova-plugin-geolocation" source="npm"/>
<gap:plugin name="cordova-plugin-network-information" source="npm" />
<gap:plugin name="cordova-open-native-settings" source="npm" />
<gap:plugin name="cordova-plugin-dialogs" source="npm" />
<gap:plugin name="cordova-plugin-request-location-accuracy" source="npm"  spec="2.2.2" />	
<gap:plugin name="cordova-plugin-x-toast" source="npm"/>	
<gap:plugin spec="https://github.com/danwilson/google-analytics-plugin.git" source="git" />
<gap:plugin name="cordova-plugin-googlemaps" source="npm" spec="2.2.8">
	    <variable name="API_KEY_FOR_ANDROID" value="" />
	    <variable name="API_KEY_FOR_IOS" value="" />
	    <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Reason" />
	    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Reason" />
</gap:plugin>
<gap:plugin name="cordova-plugin-buildinfo" source="npm" spec="1.1.0"  />	 
<gap:plugin name="onesignal-cordova-plugin" source="npm"  spec="2.4.0"/>
```

**Current behavior:**
I am using the latest cordova-plugin-googlemaps (NPM) with the latest onesignal-cordova-plugin (NPM) on PhoneGap Build. The build works fine and there are no errors, but when launching the application it crashes right away. There's no way to even get in. I've tested it by removing either the OneSignal or the Google Maps plugin and in both cases the application works, only when they are used together it crashes.

I managed to get it working by using Google Maps 2.2.8 and OneSignal 2.4.0, but obviously using old versions is not a permanent solution.

**Expected behavior:**
Application working normally.

**Related code, data or error log (please format your code or data):**

Here is the build log of the CRASHING build (using latest versions of both plugins):

```
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:11.+
cordova.system.library.2=com.android.support:support-v4:26.+
cordova.system.library.3=com.android.support:appcompat-v7:26.+
cordova.system.library.4=com.onesignal:OneSignal:3.10.1
cordova.gradle.include.1=onesignal-cordova-plugin/app-build-extras-onesignal.gradle
cordova.system.library.5=com.google.android.gms:play-services-analytics:11.0.1
```

And here is the build log of the WORKING build (OneSignal 2.4.0 and Google Maps 2.2.8):

```
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:11.+
cordova.system.library.2=com.google.android.gms:play-services-analytics:11.0.1
cordova.system.library.3=com.android.support:support-v4:26.+
cordova.system.library.4=com.android.support:appcompat-v7:26.+
cordova.gradle.include.1=cordova-plugin-googlemaps/app-tbxml-android.gradle
cordova.system.library.5=com.google.android.gms:play-services-maps:11.8.0
cordova.system.library.6=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.7=com.android.support:support-core-utils:24.1.0
cordova.system.library.8=com.onesignal:OneSignal:3.9.0
cordova.gradle.include.2=onesignal-cordova-plugin/app-build-extras-onesignal.gradle
```

**Comment by makers-mark** [comment]
The Google play-services version has to jive with every other plugin. Your's do not.

**Comment by wf9a5m75** [comment]
@spinninghamster v2.2.8 is too old at least. Please reinstall the latest version 2.3.11.

If you still get the crash, please share your project files on Github.

**Comment by spinninghamster** [comment]
@makers-mark @wf9a5m75 

I did that indeed. I changed 
`<gap:plugin name="cordova-plugin-googlemaps" source="npm" spec="2.2.8">`
to
`<gap:plugin name="cordova-plugin-googlemaps" source="npm">`

to use the latest version and that's when I get the crash.

**Comment by spinninghamster** [comment]
Working on sharing the project files on Github. Will update when it's ready.

**Comment by spinninghamster** [comment]
@wf9a5m75 Here is the project on Github:
https://github.com/spinninghamster/spinninghamsterapp

Note that I am including the **working** configuration, which is:

```
<gap:plugin name="cordova-plugin-googlemaps" source="npm" spec="2.2.8">
<gap:plugin name="onesignal-cordova-plugin" source="npm"  spec="2.4.0"/>
```

If I change it to:

```
<gap:plugin name="cordova-plugin-googlemaps" source="npm">
<gap:plugin name="onesignal-cordova-plugin" source="npm"/>
```

it crashes. It also crashes when I explicitly set it to the latest version of both.

It works only if I remove either or the other. I would greatly appreciate it if you can give me any further help on this. I've been trying to figure this out on my own for hours every day without any luck.

Note it's just a super basic app. If the PhoneGap splash screen shows, it works. If it crashes, it will crash before anything even shows.

**Comment by wf9a5m75** [comment]
Thank you for sharing your project files.
Here is the crash log.

It seems firebase library failed, but this plugin does not use it.
Thus, `onesignal-cordova-plugin` developer has to take care of it. Please ask to them.

```
    
    --------- beginning of crash
08-21 10:37:28.038 27867-27867/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spinninghamster.app, PID: 27867
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/base.apk"],nativeLibraryDirectories=[/data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/lib/arm64, /system/fake-libs64, /data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by spinninghamster** [comment]
@wf9a5m75 Thank you very much :) I will inform them.

**Comment by jkasten2** [comment]
@spinninghamster @wf9a5m75 I believe updating to PhoneGap cli-8.0.0 will fix this issue. This is because PhoneGap cli-8.0.0 will update to Cordova to Android Platform version 7.0.0. In this platform version AGP (Android Gradle Plugin) was updated to 3.0. This is required for the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) to align versions of both GMS and Firebase to 15+ used by this maps plugin.

**Comment by makers-mark** [comment]
Great information Josh, thanks!

**Comment by wf9a5m75** [comment]
Thanks @jkasten2 

Let me know the result please, @spinninghamster

**Comment by wf9a5m75** [comment]
@spinninghamster ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread. But you can still reply anytime.
