### ISSUE TITLE
Problem installing cordova-plugin-googlemaps with cordova-android 7.1.0

### ISSUE THREAD

**Issue by sergiomedinavalentin** [mapsplugin/cordova-plugin-googlemaps#2424]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fingerprint-aio 1.3.8 "FingerprintAllInOne"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
```

**Current behavior:**
``` 
I have updated my Ionic application to cordova android 7.1.0 and when I want to install cordova-plugin-googlemaps I get an error that the AndroidManifest.xml file can not be found.
```

**Expected behavior:**
```
That the plugin install correctly
```

**Related code, data or error log (please format your code or data):**
```
Installing "cordova-plugin-googlemaps" for android
Failed to install 'cordova-plugin-googlemaps': Error: ENOENT: no such file or directory, open '/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/Users/sergiomedinavalentin/.nvm/versions/node/v8.9.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/sergiomedinavalentin/.nvm/versions/node/v8.9.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/sergiomedinavalentin/.nvm/versions/node/v8.9.1/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/sergiomedinavalentin/.nvm/versions/node/v8.9.1/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: ENOENT: no such file or directory, open '/Users/sergiomedinavalentin/Desarrollo/SmartNode/bclose/bclose-app/platforms/android/AndroidManifest.xml'
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=AIza... exited with exit code 1.
```

Thanks!

**Comment by homeportcz** [comment]
Have you tried remove and add android platform?

**Comment by sergiomedinavalentin** [comment]
Yes, many times and the result is the same

**Comment by wf9a5m75** [comment]
Can not reproduce your issue.

```
masashi-macgms:test masashi$ cordova create myapp com.mycompany.myteam.myapp MyApp
Creating a new cordova project.
masashi-macgms:test masashi$ cd myapp/
masashi-macgms:myapp masashi$ ls
config.xml	package.json	plugins		www
hooks		platforms	res
masashi-macgms:myapp masashi$ cd platforms/
masashi-macgms:platforms masashi$ ls
masashi-macgms:platforms masashi$ cd ..
masashi-macgms:myapp masashi$ cordova platform list
Installed platforms:
  
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
masashi-macgms:myapp masashi$ cordova -v
8.0.0
masashi-macgms:myapp masashi$ npm -g install cordova
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
/Users/masashi/.nvm/versions/node/v9.3.0/bin/cordova -> /Users/masashi/.nvm/versions/node/v9.3.0/lib/node_modules/cordova/bin/cordova
+ cordova@8.0.0
updated 19 packages in 17.531s
masashi-macgms:myapp masashi$ cordova -v
8.0.0
masashi-macgms:myapp masashi$ cordova -v
masashi-macgms:myapp masashi$ cordova platform list
Installed platforms:
  
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
masashi-macgms:myapp masashi$ cordova platform add android@7.1.0
Using cordova-fetch for cordova-android@7.1.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.mycompany.myteam.myapp
	Name: MyApp
	Activity: MainActivity
	Android target: android-27
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.1.0
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~7.1.0 into config.xml file ...
masashi-macgms:myapp masashi$ cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="hoge" --variable API_KEY_FOR_IOS="hoge"
Installing "cordova-plugin-googlemaps" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app

      Official document https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/README.md Please consider to buy a beer for us 🍺 https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer
    
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
```

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on Github.

**Comment by alex-polosky** [comment]
@sergiomedinavalentin Two things here:
1) You really should strip out any api keys from screenshots/log outputs. Those are given to you by Google for use by your application only. If anyone gets those keys, they would be able to (ab)use those keys however they wish.

2) Your error is telling you exactly what is wrong: `no directory "...platforms/android/AndroidManifest.xml"`
This implies that the android platform has not been added.

You're using ionic correct? In order to resolve this, run `ionic cordova platform rm android`  then make sure to remove the platforms/android directory if it still exists.

Then run `ionic cordova platform add android@7.1.0`, or whichever version you want to install. Make sure to pay attention to any errors that occur.

If it fails to install the platform, you'll need to remove any plugins that reference android until you can get the platform installed properly, then readd the plugins that were removed.

**Comment by sergiomedinavalentin** [comment]
@alex-polosky thanks for your advice, I forgot to delete all the api keys.

I have managed to make it work by installing the plugin before installing the platform. It's the only way I've found to make it work.

Thanks for the help guys!
