### ISSUE TITLE
Androidのmonacaデバッガーが起動しなくなる

### ISSUE THREAD

**Issue by yesman99** [mapsplugin/cordova-plugin-googlemaps#2443]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

Cordovaバージョン
CLIバージョン 7.1.0
Androidプラットフォーム 6.4.0

開発者様、お世話になっております。

最新バージョン（2.4.6）にてこちらのプラグインを含めてMonacaカスタムデバッガーをビルドしたところ、手元のAndroid（ver7.1.1）にてアプリが起動しなくなりました。
詳細には起動時の青いログイン画面でログイン情報を入力すると100%クラッシュします。

お手数をおかけしますが、よろしくお願いいたします。

**Screen capture or video record:**
![photo_18-09-30-21-53-34 461](https://user-images.githubusercontent.com/6134076/46257818-56638c00-c4fb-11e8-8664-7bbcdfe9b9a1.png)
![photo_18-09-30-21-53-31 283](https://user-images.githubusercontent.com/6134076/46257817-55325f00-c4fb-11e8-8ca1-5910c99888d4.png)

**Related code, data or error log (please format your code or data):**
Monacaで「最小限のテンプレート」にこちらのプラグインを含めたものになります。
[project.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/2431562/project.zip)

「adb logcat *:E」でのクラッシュ時のログになります。

```
09-30 21:29:34.918  8411  8411 E AndroidRuntime: FATAL EXCEPTION: main
09-30 21:29:34.918  8411  8411 E AndroidRuntime: Process: com.example.helloworld, PID: 8411
09-30 21:29:34.918  8411  8411 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/KeyEventCompat;
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:526)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4376)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4347)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3898)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3951)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3917)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4044)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3925)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4101)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3898)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3951)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3917)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3925)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3898)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6291)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6265)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6226)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3693)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
09-30 21:29:34.918  8411  8411 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.KeyEventCompat" on path: DexPathList[[zip file "/data/app/com.example.helloworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.helloworld-1/lib/arm64, /data/app/com.example.helloworld-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /odm/lib64]]
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-30 21:29:34.918  8411  8411 E AndroidRuntime:        ... 27 more
09-30 21:29:34.937  1691  1705 E ActivityManager: Sending non-protected broadcast jp.kyocera.am.action.SHOW_APP_ERROR_DIALOG from system 1691:system/1000 pkg android
09-30 21:29:34.937  1691  1705 E ActivityManager: java.lang.Throwable
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:18282)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18854)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18945)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at android.app.ContextImpl.sendBroadcast(ContextImpl.java:881)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.AppErrorDialog.<init>(AppErrorDialog.java:142)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.AppErrors.handleShowAppErrorUi(AppErrors.java:709)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1737)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at android.os.Handler.dispatchMessage(Handler.java:102)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at android.os.Looper.loop(Looper.java:154)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at android.os.HandlerThread.run(HandlerThread.java:61)
09-30 21:29:34.937  1691  1705 E ActivityManager:       at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-30 21:29:35.509  2956  8512 E ActivityThread: Failed to find provider info for com.kyocera.outdoorreport.activityprovider
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities: Failed to openInputStream
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities: java.io.FileNotFoundException: No content provider: content://com.kyocera.outdoorreport.activityprovider/ActivityImage.png
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1135)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:986)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at android.content.ContentResolver.openInputStream(ContentResolver.java:706)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at jp.kyocera.kyocerahome.launcher.outdoorportal.OutdoorPortalUtilities.getOutdoorPortalWallpaperImage(OutdoorPortalUtilities.java:63)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at jp.kyocera.kyocerahome.launcher.outdoorportal.OutdoorPortalSlideView$LoadImage.doInBackground(OutdoorPortalSlideView.java:51)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at jp.kyocera.kyocerahome.launcher.outdoorportal.OutdoorPortalSlideView$LoadImage.doInBackground(OutdoorPortalSlideView.java:50)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-30 21:29:35.510  2956  8512 E OutdoorPortalUtilities:        at java.lang.Thread.run(Thread.java:761)
09-30 21:29:35.911  1691  8488 E DropBoxManagerService: /system/vendor/bin/logwork is not exist!!
```

**Comment by yesman99** [comment]
早速のご返答をありがとうございました。
ご教示いただいたオプション設定でデバッガーアプリが起動することが確認できました。

ありがとうございました。
