### ISSUE TITLE
Installation failed for ios 

### ISSUE THREAD

**Issue by joelchucn** [mapsplugin/cordova-plugin-googlemaps#2450]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
org.apache.cordova.geolocation 0.3.6 "Geolocation"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

I am running this from Linux (on Mac its OK, don't use Windows so no idea) but it keep complainting about ios missing modules. Also this cause another side effect - the phonegap serve cmd failed (not moving files to serve) 

**Expected behavior:**
Install plugin without error

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Installing "cordova-plugin-googlemaps" for android


Android Studio project detected

Subproject Path: CordovaLib

Subproject Path: app


      Official document https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/README.md Please consider to buy a beer for us 🍺 https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer
    


Installing "cordova-plugin-googlemaps" for browser



      Official document https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/README.md Please consider to buy a beer for us 🍺 https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer
    


Plugin "cordova-plugin-googlemaps" already installed on ios.

Adding cordova-plugin-googlemaps to package.json

Saved plugin info for "cordova-plugin-googlemaps" to config.xml

Unable to load PlatformApi from platform. Error: Cannot find module 'unorm'

(node:30572) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-common/src/events.js:71:17)
    at Object.getPlatformApiFunction (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/util.js:499:20)
    at Object.getPlatformApi (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/src/platforms/platforms.js:55:25)
    at /home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/prepare.js:105:45
    at _fulfilled (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/home/joel/.npm-packages/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:108:17)

(node:30572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by wf9a5m75** [comment]
```
$> cordova platform rm ios

$> cordova platform add ios
```

**Comment by wf9a5m75** [comment]
https://www.google.com/search?q=Unable+to+load+PlatformApi+from+platform.+Error%3A+Cannot+find+module+%27unorm%27&rlz=1C5CHFA_enUS717US717&oq=Unable+to+load+PlatformApi+from+platform.+Error%3A+Cannot+find+module+%27unorm%27&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8

**Comment by wf9a5m75** [comment]
https://issues.apache.org/jira/browse/CB-13508

**Comment by wf9a5m75** [comment]
It seems the error is not this plugin's bug.
(I haven't never used `unorm` module)

Tentatively, you just install it using npm
```
$> npm i unorm --save
```

**Comment by wf9a5m75** [comment]
ping
