### ISSUE TITLE
CordovaGoogleMaps `onStop()` calls `super.onStart()`

### ISSUE THREAD

**Issue by JordyLangen** [mapsplugin/cordova-plugin-googlemaps#2603]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
```

**Related code, data or error log (please format your code or data):**

[CordovaGoogleMaps.java:489](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/3f6ce0f97b1ac2aafcb35c389a9dec7031b7054b/src/android/plugin/google/maps/CordovaGoogleMaps.java#L498)

**Issue**

I was investigating a crash we had on Android 9 with this plugin (stacktrace for reference)

```
Caused by java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
       at plugin.google.maps.CordovaGoogleMaps.onStop(CordovaGoogleMaps.java:506)
       at org.apache.cordova.PluginManager.onStop(PluginManager.java:286)
       at org.apache.cordova.CordovaWebViewImpl.handleStop(CordovaWebViewImpl.java:471)
       at org.apache.cordova.CordovaActivity.onStop(CordovaActivity.java:289)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1432)
       at android.app.Activity.performStop(Activity.java:7653)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4373)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4351)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4426)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

And noticed that the `onStop()` method is overridden, but calls `super.onStart()` instead of `onStop()`

**Comment by wf9a5m75** [comment]
Thanks. Please send a pull request.
