### ISSUE TITLE
Bug on add Multiples markers

### ISSUE THREAD

**Issue by danielferrarip08** [mapsplugin/cordova-plugin-googlemaps#2660]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
 cordova plugin list
call-number 0.0.2 "Cordova Call Number Plugin"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
cordova-base64-to-gallery 4.1.3 "base64ToGallery"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-daniel-readcalls 0.0.1 "ReadCalls"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-fingerprint-aio 1.7.0 "FingerprintAllInOne"
cordova-plugin-firebasex 5.0.0 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.6.3-20190614-1928 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-local-notification 0.8.4 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.3.3"
@ionic-native/google-maps : "^4.14.0"
```

**Current behavior:**

On add multiple markers in map and click the app crash. Approximately 5000 markers.

```
 --------- beginning of crash
2019-07-22 10:29:39.247 29877-29877/air.com.inside.mobvendas E/AndroidRuntime: FATAL EXCEPTION: main
    Process: air.com.inside.mobvendas, PID: 29877
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
        at plugin.google.maps.PluginMap.onMarkerClick(PluginMap.java:2261)
        at com.google.android.gms.maps.zzb.zza(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzas.dispatchTransaction(Unknown Source:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:671)
        at hm.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):8)
        at com.google.android.gms.maps.internal.be.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):4)
        at com.google.maps.api.android.lib6.impl.dj.c(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):32)
        at com.google.maps.api.android.lib6.gmm6.api.f.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):40)
        at com.google.maps.api.android.lib6.gmm6.vector.n.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):35)
        at com.google.maps.api.android.lib6.gmm6.vector.ah.b(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):140)
        at com.google.maps.api.android.lib6.gmm6.vector.da.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):22)
        at com.google.maps.api.android.lib6.impl.gesture.a.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):240)
        at com.google.maps.api.android.lib6.impl.gesture.c.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
2019-07-22 10:29:39.256 29877-29877/? E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
        at plugin.google.maps.PluginMap.onMarkerClick(PluginMap.java:2261)
        at com.google.android.gms.maps.zzb.zza(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzas.dispatchTransaction(Unknown Source:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:671)
        at hm.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):8)
        at com.google.android.gms.maps.internal.be.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):4)
        at com.google.maps.api.android.lib6.impl.dj.c(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):32)
        at com.google.maps.api.android.lib6.gmm6.api.f.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):40)
        at com.google.maps.api.android.lib6.gmm6.vector.n.a(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):35)
        at com.google.maps.api.android.lib6.gmm6.vector.ah.b(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):140)
        at com.google.maps.api.android.lib6.gmm6.vector.da.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):22)
        at com.google.maps.api.android.lib6.impl.gesture.a.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):240)
        at com.google.maps.api.android.lib6.impl.gesture.c.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@17785079@17.7.85 (100306-253824076):9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Expected behavior:**
On click in marker the app not crash

**Screen capture or video record:**

[video.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3417750/video.zip)

**Related code, data or error log (please format your code or data):**

```
 let markerOptions: MarkerOptions = {
            position: { lat: this.prospects[index].geoLatitude, lng: this.prospects[index].geoLongitude }
          };

          this.map.addMarker(markerOptions)
            .then((marker: Marker) => {
              marker.on(GoogleMapsEvent.MARKER_CLICK)
                .subscribe(() => {
                  this.dadosProspect = this.prospects[index];
                  this.showInfo = true;
                  this.ngZone.run(() => { });
                  this.map.setOptions({ gestures: { scroll: false } });
                });

```

**Comment by wf9a5m75** [comment]
Too much markers. Use marker cluster

**Comment by danielferrarip08** [comment]
I'm trying to use the marketCluster however on leaving the screen it gives the following video error, could you help me?
```
Error: Uncaught (in promise): TypeError: Cannot set property 'markercluster_900469270489-marker_1541283279961' of undefined
TypeError: Cannot set property 'markercluster_900469270489-marker_1541283279961' of undefined
    at Marker.<anonymous> (/build/45.js:2663)
    at Marker.callback (/plugins/cordova-plugin-googlemaps/www/BaseClass.js:164)
    at /plugins/cordova-plugin-googlemaps/www/BaseClass.js:78
    at Array.forEach (<anonymous>)
    at Marker.trigger (/plugins/cordova-plugin-googlemaps/www/BaseClass.js:70)
    at Marker.remove (/plugins/cordova-plugin-googlemaps/www/Marker.js:120)
    at /plugins/cordova-plugin-googlemaps/www/MarkerCluster.js:337
    at Array.forEach (<anonymous>)
    at MarkerCluster.remove (/plugins/cordova-plugin-googlemaps/www/MarkerCluster.js:336)
    at clearObj (/plugins/cordova-plugin-googlemaps/www/Map.js:717)
    at Map.remove (/plugins/cordova-plugin-googlemaps/www/Map.js:726)
    at callInstance (vendor.js:58646)
    at vendor.js:58811
    at vendor.js:47088
    at new t (polyfills.js:3)
    at tryNativePromise (vendor.js:47087)
    at getPromise (vendor.js:47095)
    at GoogleMap.<anonymous> (vendor.js:58794)
    at GoogleMap.value [as remove] (vendor.js:105647)
    at ProspectsProximidadePage.webpackJsonp.998.ProspectsProximidadePage.ionViewDidLeave (/build/45.js:8523)
    at ViewController._lifecycle (vendor.js:17315)
    at ViewController._didLeave (vendor.js:17245)
    at NavControllerBase._didLeave (vendor.js:44809)
    at NavControllerBase._transitionFinish (vendor.js:44620)
    at vendor.js:44602
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4657)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at NgZone.run (vendor.js:4525)
    at vendor.js:44601
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4657)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4648)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at tryNativePromise (vendor.js:47087)
    at getPromise (vendor.js:47095)
    at GoogleMap.<anonymous> (vendor.js:58794)
    at GoogleMap.value [as remove] (vendor.js:105647)
    at ProspectsProximidadePage.webpackJsonp.998.ProspectsProximidadePage.ionViewDidLeave (/build/45.js:8523)
    at ViewController._lifecycle (vendor.js:17315)
    at ViewController._didLeave (vendor.js:17245)
    at NavControllerBase._didLeave (vendor.js:44809)
    at NavControllerBase._transitionFinish (vendor.js:44620)
    at vendor.js:44602
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4657)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at NgZone.run (vendor.js:4525)
    at vendor.js:44601
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4657)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4648)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
```

[video.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3418796/video.zip)

**Comment by wf9a5m75** [comment]
Please share your project files on github repository.

**Comment by danielferrarip08** [comment]
This is my code, it's helpful?

```
this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {

        let markers: Array<MarkerOptions> = [];
        this.prospects.forEach(element => {
          markers.push({
            position: { lat: element.geoLatitude, lng: element.geoLongitude },
            prospect: JSON.stringify(element)
          });
        });

        let markerOptions: MarkerClusterOptions = {
          icons: [{ url: '', min: 10, max: 50, }, { url: '', min: 51, max: 100, }],
          markers: markers,
          boundsDraw: false
        };

        this.map.addMarkerCluster(markerOptions)
          .then((markerCluster: MarkerCluster) => {
            this.loader.dismiss();

            markerCluster.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe((marker) => {
                this.dadosProspect = JSON.parse(marker[1].get("prospect"));
                this.showInfo = true;
                this.ngZone.run(() => { });
                this.map.setOptions({ gestures: { scroll: false } });
              });
          });
      });
```

**Comment by wf9a5m75** [comment]
If you want me to help, please share your project files on git repository. Otherwise, please debug by yourself. I'm super busy, and I'm not free helping service.

**Comment by danielferrarip08** [comment]
Link of my project and video how to simulate the problem, I look forward to your help to solve this problem.

https://github.com/danielferrarip08/errormaps

[video.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/3422679/video.zip)

**Comment by wf9a5m75** [comment]
No zip file please. I hate zip file. Please post your video to youtube.

**Comment by danielferrarip08** [comment]
Sorry, try this link,

https://youtu.be/jkcpl-1jadM

**Comment by EglisonHenrique** [comment]
Hello, I have the same problem, any solution?

**Comment by wf9a5m75** [comment]
@danielferrarip08 It seems this is a bug of ionic-native/google-maps plugin, but no longer support for `@ionic-native/google-maps@4.x (for ionic3)`

**Comment by wf9a5m75** [comment]
I noticed one thing. If I don't click on a marker ( = don't open the info panel ), the error does not occur.

**Comment by wf9a5m75** [comment]
@danielferrarip08 Okay, I prevent the error. Please reinstall the maps plugin from the `multiple_maps` branch.
