### ISSUE TITLE
Android. Crash on splash screen

### ISSUE THREAD

**Issue by rstylesoftlab** [mapsplugin/cordova-plugin-googlemaps#2666]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-advanced-http 2.0.4 "Advanced HTTP plugin"
cordova-plugin-antitampering 0.3.0 "Anti-Tampering"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-decimal-keyboard-wkwebview 1.0.3 "Decimal Keyboard"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.1 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.3-rs "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-iroot 0.8.0 "iRoot"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova.plugins.diagnostic 4.0.11 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

```

```
@ionic-native/core : "4.20.0"
@ionic-native/google-maps : "4.21.0"
```

**Current behavior:**
The application crashed on splash screen on device with old version Google Play Services (tested with version 11.7.43 (470-172403884))
With version 18.3.82 (040700-260264002) of Google Play Services crash did not appear
**Expected behavior:**
No crash or show suggestion to install new version of Google Play services

--->

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void plugin.google.maps.MyPluginLayout.stopTimer()' on a null object reference
at plugin.google.maps.CordovaGoogleMaps.onOverrideUrlLoading(CordovaGoogleMaps.java:220)
at org.apache.cordova.PluginManager.onOverrideUrlLoading(PluginManager.java:451)
at org.apache.cordova.CordovaWebViewImpl$EngineClient.onNavigationAttempt(CordovaWebViewImpl.java:603)
at org.apache.cordova.engine.SystemWebViewClient.shouldOverrideUrlLoading(SystemWebViewClient.java:79)
at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:339)
at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:256)
at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository

**Comment by rstylesoftlab** [comment]
Unfortunately, I cannot provide access to the source code of the project.

**Comment by wf9a5m75** [comment]
In that case, I can't help you unfortunately. Regarding of the log, you seems try to create a map before available. Please check your code.
