### ISSUE TITLE
Null Pointer Request on Android

### ISSUE THREAD

**Issue by tryhardest** [mapsplugin/cordova-plugin-googlemaps#2732]
We have a FATAL EXCEPTION that is newly appearing in Android 8.1.1 when going to the map. The markers for places show up (briefly before app crash) but we also have a custom cropped user avatar on the map that comes from an AWS Lambda function. We think this might be the cause because no changes in versioning are introduced recently, and it worked not long ago.

Also before the crash occurs, we have not yet seen that cropped user avatar. This was working mere weeks ago. 

I have attached 5 batch logcats of the crash below and wonder if you are able to see in them the possible cause. It appears there is a 'CAUSED BY' in each of them that refers to a Null Pointer Request. We do see the map for a second before the crash on each attempt. Thank you. 

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

    "com.fedirts.cameraroll": "file:custom-plugins/com.fedirts.cameraroll",
    "cordova": "^9.0.0",
    "cordova-android": "^8.0.0",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-background-geolocation-lt": "^3.0.5",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-android-notch": "1.0.3",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-background-fetch": "^5.4.1",
    "cordova-plugin-badge": "~0.8.8",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-cocoalumberjack": "0.0.4",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "~2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-googlemaps": "^2.6.2",
    "cordova-plugin-googleplus": "^5.3.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "2.1.3",
    "cordova-plugin-ionic-webview": "^2.4.0",
    "cordova-plugin-ios-camera-permissions": "^1.2.0",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-media": "^5.0.2",
    "cordova-plugin-media-capture": "^3.0.2",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-purchase": "^8.1.1",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-streaming-media": "git+https://github.com/nchutchind/cordova-plugin-streaming-media.git",
    "cordova-plugin-video-editor": "^1.1.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^3.2.0",
    "cordova-support-google-services": "^1.2.1",
    "cordova.plugins.diagnostic": "^4.0.12",
    "es6-promise-plugin": "^4.2.2",
    "most-observable": "0.0.2",
    "pushwoosh-cordova-plugin": "^7.16.0"

**Current behavior:**
On nav to map, the app crashes.

**Expected behavior:**
Map to open with our cropped avatar from AWS-cloudfront

**Related code, data or error log (please format your code or data):**
Here are 5 examples of the logcat crash

```
01-20 10:23:42.817 27372 27399 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1

01-20 10:23:42.817 27372 27399 E AndroidRuntime: Process: com.mapfindme.mapfindme, PID: 27372
01-20 10:23:42.817 27372 27399 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.addBitmapToMemoryCache(AsyncLoadImage.java:80)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:557)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-20 10:23:42.817 27372 27399 E AndroidRuntime: ... 4 more
01-20 10:23:42.906 698 698 E lowmemorykiller: Error writing /proc/27372/oom_score_adj; errno=22
01-20 10:23:43.055 698 698 E lowmemorykiller: Error writing /proc/27433/oom_score_adj; errno=22
01-20 10:23:43.362 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99018 pid 27433: Permission denied
01-20 10:23:43.610 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99017 pid 26569: Permission denied

01-20 10:31:51.041 29625 29704 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
01-20 10:31:51.041 29625 29704 E AndroidRuntime: Process: com.mapfindme.mapfindme, PID: 29625
01-20 10:31:51.041 29625 29704 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.addBitmapToMemoryCache(AsyncLoadImage.java:80)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:557)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-20 10:31:51.041 29625 29704 E AndroidRuntime: ... 4 more
01-20 10:31:53.532 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99020 pid 29728: Permission denied
01-20 10:31:55.150 984 3672 E InputDispatcher: Window handle Window{c1a30ae u0 Application Error: com.mapfindme.mapfindme} has
no registered input channel
01-20 10:31:55.167 984 3026 E InputDispatcher: Window handle Window{c1a30ae u0 Application Error: com.mapfindme.mapfindme} has
no registered input channel
01-20 10:32:01.523 29977 29977 E mapFindme.mapfindme: Unknown bits set in runtime_flags: 0x8000
01-20 10:32:03.073 652 30023 E ResolverController: No valid NAT64 prefix (105, /0)
01-20 10:32:03.136 652 30025 E ResolverController: No valid NAT64 prefix (105, /0)
01-20 10:32:03.812 652 30041 E ResolverController: No valid NAT64 prefix (105, /0)
01-20 10:32:05.509 698 698 E lowmemorykiller: Error writing /proc/28242/oom_score_adj; errno=22

01-20 10:33:07.148 30362 30389 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
01-20 10:33:07.148 30362 30389 E AndroidRuntime: Process: com.mapfindme.mapfindme, PID: 30362
01-20 10:33:07.148 30362 30389 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.addBitmapToMemoryCache(AsyncLoadImage.java:80)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:557)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-20 10:33:07.148 30362 30389 E AndroidRuntime: ... 4 more
01-20 10:33:07.996 698 698 E lowmemorykiller: Error writing /proc/28644/oom_score_adj; errno=22
01-20 10:33:08.018 652 30690 E ResolverController: No valid NAT64 prefix (105, /0)
01-20 10:33:09.716 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99022 pid 30412: Permission denied

01-20 10:33:57.625 30750 30778 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
01-20 10:33:57.625 30750 30778 E AndroidRuntime: Process: com.mapfindme.mapfindme, PID: 30750
01-20 10:33:57.625 30750 30778 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.addBitmapToMemoryCache(AsyncLoadImage.java:80)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:557)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-20 10:33:57.625 30750 30778 E AndroidRuntime: ... 4 more
01-20 10:33:58.948 652 31026 E ResolverController: No valid NAT64 prefix (105, /0)
01-20 10:34:00.112 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99023 pid 30801: Permission denied

01-20 10:39:55.545 2155 2354 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
01-20 10:39:55.545 2155 2354 E AndroidRuntime: Process: com.mapfindme.mapfindme, PID: 2155
01-20 10:39:55.545 2155 2354 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.addBitmapToMemoryCache(AsyncLoadImage.java:80)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:557)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-20 10:39:55.545 2155 2354 E AndroidRuntime: ... 4 more
01-20 10:39:55.584 698 698 E lowmemorykiller: Error writing /proc/2155/oom_score_adj; errno=22
01-20 10:39:55.828 984 1126 E libprocessgroup: Error encountered killing process cgroup uid 99034 pid 2245: Permission denied`
```

**Comment by wf9a5m75** [comment]
I think too much markers

**Comment by tryhardest** [comment]
@wf9a5m75 so max markers we plot is 20, with 1 user avatar (the AWS cropped img avatar). Even when mapping self (so 1 avatar), it crashes.

Also it didn't crash ever on plotting many markers till a few weeks ago and we feel the users avatar crashes it.

A) why do you think that when it worked for so long?
B) I want to mention the 5 'blocks' of logcat errors are 5 individual crash traces. Space separates each.

Thanks.

**Comment by tryhardest** [comment]
Similarly  on iOS, the error message is:

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: 7766892924502085506/32,32)' terminating with uncaught exception of type NSException

**Comment by tryhardest** [comment]
What we do is get a PNG image from an AWS lambda, cache the image locally (using [imgcache](https://github.com/chrisben/imgcache.js/)), and then get the nativeURL (file:///) of the file (using the [Cordova File plugin](https://github.com/apache/cordova-plugin-file)) and supply that to the map.addMarker method.

**Comment by tryhardest** [comment]
2+ weeks of work right here to determine that;

On iOS, the problem is the version of imgcache. The latest is 2.1.1, and using that with webview 2.5.2, the map crashes with custom avatar. Reverting to imgcache version 2.0.0 (which is what we used previously), causes the map avatar to show without the map crashing on iOS. On Android, reverting imgcache alone doesn't fix the problem. Reverting from webview plugin version 2.5.2 to 2.5.1 ixes the issue (map avatar shows and app doesn't crash). However, reverting to 2.4.0 didn't fix the issue. This may explain why some older builds didn't work that formerly did, until we were using webview plugin version 2.4.0. 

Thanks for your reply @wf9a5m75

**Comment by wf9a5m75** [comment]
Did you try the `multiple_maps` branch (as I replied to your email)?
