### ISSUE TITLE
Crash 'ConcurrentModificationException' on Android 9 [v3.2.6]

### ISSUE THREAD

**Issue by eviv3k** [mapsplugin/cordova-plugin-googlemaps#2744]
Issue:

java.lang.RuntimeException: Unable to pause activity {package.example.MainActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4344)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4299)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4251)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7285)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
        at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
        at org.apache.cordova.PluginManager.onPause(PluginManager.java:209)
        at org.apache.cordova.CordovaWebViewImpl.handlePause(CordovaWebViewImpl.java:435)
        at org.apache.cordova.CordovaActivity.onPause(CordovaActivity.java:245)
        at android.app.Activity.performPause(Activity.java:7672)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4334)
        ... 12 more

Do you have any solution for this problem?

**Comment by wf9a5m75** [comment]
I can't see any information related with this plugin.

**Comment by eviv3k** [comment]
**Cordova Information:**
`cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-camera-preview 0.11.1 "cordova-plugin-camera-preview"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-flashlight 3.2.0 "Flashlight"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-save-image 0.3.0 "SaveImage"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
`

**Comment by wf9a5m75** [comment]
In order to detect what's the problem, please create a simple new project that reproduce your issue.

**Comment by wf9a5m75** [comment]
I'm not your free support. Please do your best as much as possible.

**Comment by HansKrywaa** [comment]
The Issue you mentioned here happens for my users too, but it is not related to this Plugin. This is a `cordova-android` Issue i think. See: https://github.com/apache/cordova-android/issues/924
