### ISSUE TITLE
PhoneGap Build fails with version 2.7.0

### ISSUE THREAD

**Issue by jiristanglica** [mapsplugin/cordova-plugin-googlemaps#2758]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-googlemaps 2.7.0 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-youtube-video-player 2.4.0 "CordovaYoutubeVideoPlayer"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
phonegap-plugin-push 1.11.1 "PushPlugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**
The build on PhoneGap Build fails for iOS with the plugin version 2.7.0.
If downgraded to previously used version 2.6.2, it builds with no errors.

**Expected behavior:**

The build works fine for version 2.7.0.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
Full failing xcode build log: https://drive.google.com/open?id=1Q5nPksvWqXkJ6QyuWhl29c-eJ60Ro1Oe
Full success xcode build log: https://drive.google.com/open?id=1h5pFPuxFNrSjXeA6aMm5o2bfKQIBo7jK

Snippet from the failing build (see full build log above):
```
Ld /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat normal arm64
    cd /project
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    /Applications/Xcode101.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode101.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/private/project/build/device -L/Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/BuildProductsPath/Release-iphoneos/XCDYouTubeKit -L/project/Pods/GGLInstanceID/Libraries -L/project/Pods/GoogleCloudMessaging/Libraries -F/private/project/build/device -F/project/Pods/GoogleIPhoneUtilities/Frameworks -F/project/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/project/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/project/Pods/GoogleUtilities/Frameworks/frameworks -F/project/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -FZaslat/Plugins/com.googlemaps.ios -filelist /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat_lto.o -Xlinker -final_output -Xlinker /Applications/Zaslat.app/Zaslat -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lXCDYouTubeKit -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework JavaScriptCore -framework MediaPlayer -framework OneSignal -framework SystemConfiguration -framework UIKit -framework UserNotifications /project/build/device/libCordova.a -weak_framework AudioToolbox -framework SystemConfiguration -lPods-Zaslat -framework AddressBook -lsqlite3 -lz -weak_framework WebKit -framework Accelerate -framework CoreData -framework CoreLocation -framework CoreTelephony -framework CoreText -framework CoreImage -framework GLKit -framework ImageIO -lc++ -framework OpenGLES -framework QuartzCore -framework UIKit -framework GoogleMapsBase -framework GoogleMaps -framework GoogleMapsCore -framework MediaPlayer -framework AVFoundation -framework JavaScriptCore -Xlinker -dependency_info -Xlinker /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat_dependency_info.dat -o /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat
ld: warning: directory not found for option '-L/Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/BuildProductsPath/Release-iphoneos/XCDYouTubeKit'
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[GMSx_GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] in GoogleMapsBase
      -[UIView(GMSSafeAreaSupport) gms_safeAreaInsets] in GoogleMaps
      -[GMSScreenInfo initWithUIScreen:] in GoogleMaps
      -[GMSx_QTMCollectionViewController viewDidLoad] in GoogleMaps
      -[GMSx_QTMCollectionViewController viewDidLayoutSubviews] in GoogleMaps
      -[GMSx_QTMCollectionViewStyleController contentViewInsetsForCellWithAttribute:] in GoogleMaps
      -[GMSx_QTMCollectionViewStyleController setInsetsContentViewsToSafeArea:] in GoogleMaps
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/armv7/Zaslat normal armv7
    cd /project
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    /Applications/Xcode101.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode101.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/private/project/build/device -L/Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/BuildProductsPath/Release-iphoneos/XCDYouTubeKit -L/project/Pods/GGLInstanceID/Libraries -L/project/Pods/GoogleCloudMessaging/Libraries -F/private/project/build/device -F/project/Pods/GoogleIPhoneUtilities/Frameworks -F/project/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/project/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/project/Pods/GoogleUtilities/Frameworks/frameworks -F/project/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -FZaslat/Plugins/com.googlemaps.ios -filelist /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/armv7/Zaslat.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/armv7/Zaslat_lto.o -Xlinker -final_output -Xlinker /Applications/Zaslat.app/Zaslat -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lXCDYouTubeKit -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework JavaScriptCore -framework MediaPlayer -framework OneSignal -framework SystemConfiguration -framework UIKit -framework UserNotifications /project/build/device/libCordova.a -weak_framework AudioToolbox -framework SystemConfiguration -lPods-Zaslat -framework AddressBook -lsqlite3 -lz -weak_framework WebKit -framework Accelerate -framework CoreData -framework CoreLocation -framework CoreTelephony -framework CoreText -framework CoreImage -framework GLKit -framework ImageIO -lc++ -framework OpenGLES -framework QuartzCore -framework UIKit -framework GoogleMapsBase -framework GoogleMaps -framework GoogleMapsCore -framework MediaPlayer -framework AVFoundation -framework JavaScriptCore -Xlinker -dependency_info -Xlinker /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/armv7/Zaslat_dependency_info.dat -o /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/armv7/Zaslat
ld: warning: directory not found for option '-L/Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/BuildProductsPath/Release-iphoneos/XCDYouTubeKit'
Undefined symbols for architecture armv7:
  "___isPlatformVersionAtLeast", referenced from:

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Library/Developer/Xcode/DerivedData/Zaslat-ehqqkfwcietsrlhhqcskyxsdsrib/Build/Intermediates.noindex/ArchiveIntermediates/Zaslat/IntermediateBuildFilesPath/Zaslat.build/Release-iphoneos/Zaslat.build/Objects-normal/arm64/Zaslat normal arm64
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Support this plugin activity**

I appreicate if you give me a beer :beer: from [here](
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Comment by wf9a5m75** [comment]
`IPHONEOS_DEPLOYMENT_TARGET=10.0` needs to 11.0

Google Maps SDK for iOS requires at least 11.0

**Comment by jiristanglica** [comment]
Oh okay, thank you!
