### ISSUE TITLE
Message "App keeps stopping"

### ISSUE THREAD

**Issue by BenjiMario** [mapsplugin/cordova-plugin-googlemaps#2823]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [ ] **iOS**

**cordova information:**

```
cordova-androidx-build 1.0.4 "cordova-androidx-build"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.8.0-20200709-2008 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.4.0 "NativeGeocoder"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-google-services 1.4.0 "cordova-support-google-services"
```
**Hitting the device's overview (square) button shows message saying "app keeps stopping"**

**Related code, data or error log (please format your code or data):**

```
java.lang.RuntimeException: Unable to stop activity {my.app.name.MainActivity}: java.lang.IllegalStateException
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4624)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException
        at com.google.android.libraries.maps.ij.zzae.zzb(Preconditions.java:29)
        at com.google.android.libraries.maps.ke.zzae.zze(MapRendererPhoenix.java:253)
        at com.google.android.libraries.maps.ka.zzba.zzC(GoogleMapImpl.java:310)
        at com.google.android.libraries.maps.ka.zzcw.zzh(MapViewDelegateImpl.java:16)
        at com.google.android.libraries.maps.MapView$zza.onStop(MapView.java:18)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onStop(Unknown Source:4)
        at com.google.android.libraries.maps.MapView.onStop(MapView.java:39)
        at plugin.google.maps.PluginMap.onStop(PluginMap.java:524)
        at org.apache.cordova.PluginManager.onStop(PluginManager.java:286)
        at org.apache.cordova.CordovaWebViewImpl.handleStop(CordovaWebViewImpl.java:473)
        at org.apache.cordova.CordovaActivity.onStop(CordovaActivity.java:291)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1466)
        at android.app.Activity.performStop(Activity.java:8018)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616)
```

**Comment by wf9a5m75** [comment]
It seems the bug of the Google Maps SDK for Android.
Please use the master branch tentatively

**Comment by BenjiMario** [comment]
Thank you very much for the fast answer.
This fixed the problem.

**Comment by wf9a5m75** [comment]
I will report this issue to Google
