### ISSUE TITLE
urgent: Problem with installing the plugin. - Unquoted attribute value

### ISSUE THREAD

**Issue by TheMassassian** [mapsplugin/cordova-plugin-googlemaps#287]
Hi there,

I tried to install the plugin on two other macbooks and was not able to install it correctly. I also got the same error. To be sure, that the problem is not caused by missing preparations I also created a new cordova project on my machine and got the same error.

Fetching plugin "plugin.google.maps" via plugin registry
npm http GET http://registry.cordova.io/plugin.google.maps
npm http 304 http://registry.cordova.io/plugin.google.maps
Plugin "plugin.google.maps" already installed on android.
Installing "plugin.google.maps" for ios
Fetching plugin "https://github.com/wf9a5m75/googlemaps-ios-sdk-for-phonegap" via git clone
Plugin "https://github.com/wf9a5m75/googlemaps-ios-sdk-for-phonegap" checked out to git ref "master".
Failed to install 'plugin.google.maps':Error: Unquoted attribute value
Line: 1
Column: 41
Char: “
    at error (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:364:22)
    at Object.write (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:913:11)
    at XMLParser.feed (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/elementtree.js:263:10)
    at Object.exports.XML (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/elementtree.js:593:13)
    at Object.module.exports.parseElementtreeSync (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/util/xml-helpers.js:126:38)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:88:35
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)
Error: Unquoted attribute value
Line: 1
Column: 41
Char: “
    at error (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:364:22)
    at Object.write (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/node_modules/sax/lib/sax.js:913:11)
    at XMLParser.feed (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/elementtree.js:263:10)
    at Object.exports.XML (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/elementtree.js:593:13)
    at Object.module.exports.parseElementtreeSync (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/util/xml-helpers.js:126:38)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:88:35
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)

**Comment by VGerris** [comment]
the above instructions vanished? In a recent version I removed the plugin and re-added it.
I keep getting a notification about a missing key, even when it was in the plugin.xml of the plugin.
The emulator works again though.
