### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkf;

### ISSUE THREAD

**Issue by roblav96** [mapsplugin/cordova-plugin-googlemaps#686]
I'm looking to see how your plugin can play nicely with Google Cloud Messaging for Android. I'm using Onesignal.

```
:preDexDebug
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkf;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/roblav96/Library/Android/build-tools/23.0.1/dx --dex --no-optimize --output /Users/roblav96/Downloads/onesignal/platforms/android/build/intermediates/dex/debug --input-list=/Users/roblav96/Downloads/onesignal/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkf;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.676 secs

/Users/roblav96/Downloads/onesignal/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/roblav96/Downloads/onesignal/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/roblav96/Downloads/onesignal/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
```
cordova 5.3.3
map plugin 1.3.4
onesignal sdk 1.1.9
android sdk tools 24.4.1
platform tools 23.0.1
android support 24
support library 23.1
play services 27
google repositories 22

It looks like these guys over here fixed this issue:
https://github.com/phonegap/phonegap-plugin-push/issues/136

I'm just not too sure how to incorporate it into my project.

Any ideas?

**Comment by Hirbod** [comment]
This is not related to our plugin, as we don't include any dependencies, we're using framework-tag. (Gradle)

Look inside your library folder and remove android-v4 or other support libs

**Comment by roblav96** [comment]
where is this folder? I did a search for the file and found nothing

**Comment by Hirbod** [comment]
Please ask on Stackoverflow, I can't give generel Cordova/Android support!
