### ISSUE TITLE
Installation broke project and now can't uninstall

### ISSUE THREAD

**Issue by MoPHL** [mapsplugin/cordova-plugin-googlemaps#723]
Today I installed this plugin with 

cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

then I ran ionic build android and got the following output

Running command: "C:\Program Files\nodejs\node.exe" D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\hooks\after_prepare\010_add_platform_class.js D:\Dropbox\NetBeansProjects\ionic\IonicShowcase
add to body class: platform-android
Running command: cmd "/s /c "D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\cordova\build.bat""
ANDROID_HOME=D:\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_60
Running: D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\gradlew cdvBuildDebug -b D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV42220Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase830Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement830Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocation830Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMaps830Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        D:\Android\android-sdk\build-tools\23.0.1\dx.bat --dex --no-optimize --output D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\build\intermediates\dex\debug --input-list=D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.906 secs

D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\gradlew cdvBuildDebug -b D:\Dropbox\NetBeansProjects\ionic\IonicShowcase\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I then attempted to uninstall the plugin with 

cordova plugin remove phonegap-googlemaps-plugin

 but got the message 

Plugin "phonegap-googlemaps-plugin" is not present in the project. See `cordova plugin list`.

which I found to be extremely weird, since I was just reverting what I did previously during the installation. I then found that the plugin actually is called plugin.google.maps  when installed, so I proceeded to try to uninstall it with 

cordova plugin remove plugin.google.maps 

but that also failed with the error message

Uninstalling plugin.google.maps from android
Uninstalling 1 dependent plugins.
Uninstalling com.googlemaps.ios from ios
TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\plist\lib\build.js:131:18)
    at walk_obj (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\plist\lib\build.js:98:7)
    at walk_obj (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\plist\lib\build.js:109:9)
    at Object.build (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\plist\lib\build.js:76:3)
    at ConfigFile_save [as save] (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\ConfigFile.js:97:47)
    at C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all] (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all] (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\config-changes.js:82:24)
    at Object.exports.process (C:\Users\Ideativity\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\config-changes.js:59:12)

And so right now I can't build my project nor can I uninstall the plugin. Anyone know what I can do to fix this?
Thanks.

**Comment by Hirbod** [comment]
If you want to uninstall, the plugin name is "plugin.google.maps" Please have a look at your "cordova plugin list"

**Comment by MoPHL** [comment]
Could you read the issue before closing it? I have tried

cordova plugin remove plugin.google.maps

but it gives me an error that I posted in my previous message.

**Comment by Hirbod** [comment]
If you don't format your issues that I can read it properly, I will not support. I'm tired of repeating myself like 1000 times for the same issues. The issue you have was discussed multiple times, the problem comes not from our plugin, multiple dex files will be caused trough old framework-files or another project that installs playservice (another version then we install)

And the "BUFFER" problem is a known cordova CLI bug. Search Apache JIRA please. The only way to fix this currently is to patch a special file or to `cordova platform rm ios`

I'm sorry!
