### ISSUE TITLE
addHole default value throws exception in native addPolygon()

### ISSUE THREAD

**Issue by smcpjames** [mapsplugin/cordova-plugin-googlemaps#762]
See PR #761. Using an empty array as the addHole default throws an exception in the native code (on Android, possibly iOS).

Android exception:

````
W/System.err(19026): Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
W/System.err(19026): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
W/System.err(19026): 	at java.util.ArrayList.get(ArrayList.java:308)
W/System.err(19026): 	at com.google.maps.api.android.lib6.e.au.c(Unknown Source)
W/System.err(19026): 	at com.google.maps.api.android.lib6.e.au.<init>(Unknown Source)
W/System.err(19026): 	at com.google.maps.api.android.lib6.e.ev.a(Unknown Source)
W/System.err(19026): 	at com.google.android.gms.maps.internal.j.onTransact(SourceFile:152)
W/System.err(19026): 	at android.os.Binder.transact(Binder.java:380)
W/System.err(19026): 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addPolygon(Unknown Source)
W/System.err(19026): 	at com.google.android.gms.maps.GoogleMap.addPolygon(Unknown Source)
W/System.err(19026): 	at plugin.google.maps.PluginPolygon.createPolygon(PluginPolygon.java:65)
W/System.err(19026): 	... 12 more
````

The Java could be modified to detect an empty array, but this change is more expedient.

**Comment by Hirbod** [comment]
fixed
