### ISSUE TITLE
problem with new version of adroid SDK?

### ISSUE THREAD

**Issue by sonrebmax** [mapsplugin/cordova-plugin-googlemaps#801]
Hello!

I have updated android SDK, now I have newest google-play-services.jar and I got these messages :( Do anyone know how solve this problem?

C:\phonegap\appname\platforms\android>gradlew -q dependencies

### Root project
 

_debugApk - ## Internal use, do not manually configure ##
+--- com.android.support:support-v13:23+ -> 23.1.1
+--- com.google.android.gms:play-services-gcm:+ -> 8.4.0
|    \--- com.google.android.gms:play-services-measurement:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0
+--- com.google.android.gms:play-services-maps:+ -> 8.4.0
+--- com.google.android.gms:play-services-location:+ -> 8.4.0
|    \--- com.google.android.gms:play-services-maps:8.4.0
\--- project :CordovaLib

Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzsu;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)

**Comment by sonrebmax** [comment]
Problem solved. I mistake added google-play-services.jar to folder "libs", it is not need.
