### ISSUE TITLE
NullPointerException: loading markers

### ISSUE THREAD

**Issue by ffabreti** [mapsplugin/cordova-plugin-googlemaps#853]
I hope I am doing something wrong, but I may be hitting a bug instead.

My app is throwing this error below:
 
```
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime: FATAL EXCEPTION: main
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime: Process: com.fabreti.Mapbug1, PID: 16981
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.longitude' on a null object reference
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at plugin.google.maps.PluginMarker$4.run(PluginMarker.java:288)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5942)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
02-16 15:54:41.565 16981-16981/com.fabreti.Mapbug1 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

[I have set up a debug APK](https://drive.google.com/file/d/0Bz9EAjPa_w23X3lpTjdOaXcydVU/view?usp=sharing) to show the error being reproduced to whoever may help.

It is a reduced and stripped version of my app, where the app user is presented with a favorite site screen and it can choose from 2 mocked favorites. One is near the user position (4 km), the other favorite is far away (400 km).

Clicking on the near one, everything works. Ionic loads a view that loads the map then:  (1) add user marker, (2) adds site marker, (3) add a blinking green marker to destiny site, (4) calculate map bounds to keep both markers on view  and (5)  moves the camera.
I did not find info in the docs about how to do things in a sequence so I am using the callbacks of each method. 

 So, if you care to debug the APK on chrome, you may see the `rota.js` file,  `initMarkers()` function on `RotaController` where the exception is being raised.

THE PROBLEM IS the code works fine with the favorite that is 4 km away from user.  But throws the exception when the user chooses the favorite that is 400 km away.  The only thing that differs both favorites are the coordinates of each.

Other info:

```
 $ ionic plugin 
cordova-plugin-crosswalk-webview 1.3.1 "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.2.1 "Whitelist"
org.apache.cordova.console 0.2.13 "Console"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"

$ ionic info
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 1.2.4
OS: Distributor ID:     Fedora Description:     Fedora release 21 (Twenty One) 
Node Version: v0.12.7
```

**Comment by ffabreti** [comment]
Here follows the `initMarkers()` function where steps 1 to 5 occurs.
Exception is happening at step 2, on `map.addMarker()`

```
var initMarkers = function(map, cback) { //native

            if (!usrMarker) {
                map.addMarker({  // #1 - add USER marker
                        markerId: 'user',
                        position: getV2UserLatLng(),
                        icon: 'blue',
                        title: 'Your Position',
                        styles: {
                            opacity: "0.8"
                        },
                        snippet: 'Defined By ' + $scope.lastPos.source,
                        animation: plugin.google.maps.Animation.BOUNCE,
                        markerClick: function (marker) {
                            marker.showInfoWindow();
                        },
                        infoClick: function (marker) {
                            marker.hideInfoWindow();
                        }
                    },
                    //callback
                    function (marker) {

                        if (!marker) {
                            if (cback) cback({success: false, message: 'Error adding usrMarker'});
                            return false;
                        }

                        usrMarker = marker;

                        if (!farMarker) {
                            var farOpts = {markerId: 'farmacia',
                                            position: getV2FarmaLatLng(),
                                            icon: 'red',
                                            title: $scope.f.razao + '',
                                            snippet: $scope.f.endereco,
                                            styles: {
                                                maxWidth: "50%"
                                            },
                                            animation: plugin.google.maps.Animation.BOUNCE,
                                            markerClick: function (marker) {
                                                marker.showInfoWindow();
                                            },
                                            infoClick: function (marker) {
                                                marker.hideInfoWindow();
                                            }
                                        };
                            map.addMarker(  // #2 - add site marker
                                farOpts,
                                //callback
                                function (marker) {

                                    if (!marker) {
                                        if (cback) cback({success: false, message: 'Error adding farMarker'});
                                        return false;
                                    }

                                    farMarker = marker;
                                    farMarker.showInfoWindow();

                                    if (!stepMarker) {
                                        map.addMarker({  // #3 - add blinking green marker to destiny (site)
                                                markerId: 'step',
                                                position: getV2FarmaLatLng(),
                                                icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wsCDjULzRjL9AAAAgFJREFUOE/Fkk1rE1EUht+5cyczTdp8NJUhmvSDLKYgaERaaRAq1B9gXPhDBMFf4NKfIK5dGFy6sKWLRkEo2JWzsAkarTVt2jExk/m6473TJMSYfQ8c5uO857nn3vsClx3SlAFU6KoxM5eq0CspQ9T9lmXaHauKY8fkn854zyQgS9fSj288elje2NpETl+JtEfHdbx/t4uDV69r/sfz5/zX6RAij9FUdS31dOvZk/LdjU0ktQRC34kyrsWxvGogcbtY+Gbu54Pv/T3eF4heOgTErqrGUqVUns/P4shtQGYMUsiicigRBIQgw2tLD26WG80PhvvDOfgHQGdoRV/PoNU3eYMPsTciACHAeDN/cCCFvj6PJte6mADEdcVw1FPYjhUBaMhzcEI+7/YlGgGI5kNoe18uZh9tgRAGhnMELkNCDaBRBkW+2IIXEPR59jxxZDKEdhgjQK/lmmB2bpavsKDyVBjmBsIOIzjxePIpbJsi0g5iBIh7rCrv/7537X4Mi4qHfCxAZjDBGV+9KctQ+QD1vR6EtjsJ+HXommSnWyvdSZdLhSQWaYCUHN0ULA5YUCisr3/Q2O7UhHaaD4Ku6X2qt938iiYXbl3PopjNIpNIwvYJdt+e4eWLdu3kTV8YqTMETLVyblUy0vyqissksvJhg5lt26/+/Bz+Z+UxI17S618Ch8o/uvXXtAAAAABJRU5ErkJggg==',
                                                title: 'passo',
                                                size: {
                                                    width: 16,
                                                    height: 16
                                                },
                                                flat: true
                                            },
                                            //callback
                                            function (marker) {

                                                if (!marker) {
                                                    if (cback) cback({success: false, message: 'Error adding stepMarker'});
                                                    return false;
                                                }

                                                stepMarker = marker;

                                                stepMarker.setIconAnchor(8, 8);

                                                stepMarkerTimer = setInterval(function () {
                                                    stepMarker.setVisible(!stepMarker.isVisible());
                                                }, 1300);

                                                if (cback) cback({success: true});
                                            }
                                        );
                                    }

                                    // #4 - calculate map bounds to visualize both markers
                                    //VIDE https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/647

                                    var latLngArray = [getV2UserLatLng(), getV2FarmaLatLng()];
                                    var bounds = new plugin.google.maps.LatLngBounds(latLngArray);

                                    var mapDimensions = { height: mapDIV.offsetHeight, width: mapDIV.offsetWidth };
                                    var zoom = getBoundsZoomLevel(bounds, mapDimensions);
                                    console.log('ZOOM: ' + zoom);

                                    //#5 - move the camera

                                    map.animateCamera({
                                        target: bounds.getCenter(),
                                        zoom: zoom,
                                        tilt: 30,
                                        duration: 3000
                                    }, function () {
                                        if (farMarker) farMarker.hideInfoWindow();
                                    });


                                }
                            );
                        }
                    }
                );
            }
```

**Comment by ffabreti** [comment]
When I change animation key on marker options from `plugin.google.maps.Animation.BOUNCE` to `plugin.google.maps.Animation.DROP` it completely works!

Is it a bug then?

**Comment by Hirbod** [comment]
Looks like. The bounce/drop animation isnt something that is available by default form google (only JS V3 API). Masashi just incorporated some StackOverflow Code into our branch. I can't tell you if this is something very nice or not.
