### ISSUE TITLE
Cordova with iOS Google Map

### ISSUE THREAD

**Issue by shivsuthanmhub** [mapsplugin/cordova-plugin-googlemaps#945]
Hi ,
First of all, I wanna know that now a days apple allowed google maps or not while upload my app in the app store.
I tried to use this nice plugin in my ios Cordova project But I can't able to proceed. I had a Cordova latest version installed in my machine Cordova @6.1.0 and Cordova iOS version is @4.1.1.
After installing the plugin using CLI the plugin was installed but while build my application I'm getting the below error as 
```
** BUILD FAILED **


The following build commands failed:
CpResource HelloMap/Resources/GoogleMaps.bundle build/emulator/HelloMap.app/GoogleMaps.bundle
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloMap/platforms/ios/cordova/build-debug.xcconfig,-project,HelloMap.xcodeproj,ARCHS=i386,-target,HelloMap,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloMap/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloMap/platforms/ios/build/sharedpch
```
So, I can't able to run the application please help me in this to use your plugin properly ASAP.

**Comment by wf9a5m75** [comment]
Please past all error logs, not only a few lines.

**Comment by shivsuthanmhub** [comment]
Hi - I think the plugin will work well for the combination of Cordova CLI 5 series and the Cordova iOS of 3.9.0 like this series i can able use the plugin but newer version i can't able to proceed.

@wf9a5m75 thanks for your msg - for more information while using the newer version errors please find below

while build using cordova CLI

Getting below error 

> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC build/HelloCoredova.build/Debug-iphonesimulator/HelloCoredova.build/Objects-normal/i386/GroundOverlay.o HelloCoredova/Plugins/plugin.google.maps/GroundOverlay.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloCoredova/platforms/ios/cordova/build-debug.xcconfig,-project,HelloCoredova.xcodeproj,ARCHS=i386,-target,HelloCoredova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloCoredova/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloCoredova/platforms/ios/build/sharedpch
> ERROR building one of the platforms: Error: /Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloCoredova/platforms/ios/cordova/build: Command failed with exit code 2
> You may not have the required environment or OS to build this project
> Error: /Users/Test/Shiv_Suthan_M_Drive/Suthan_Drive/Cordova_Dev/HelloCoredova/platforms/ios/cordova/build: Command failed with exit code 2
>     at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> eMO:HelloCoredova Test$ 

> While build directly in xcode getting below error log :


![image](https://cloud.githubusercontent.com/assets/11000006/14676299/7e42f10c-072a-11e6-8325-01545ac279ef.png)

**Comment by wf9a5m75** [comment]
Well, I (and other people) use Cordova 6.1 with this plugin (th master branch).
And the `CDVJSON.h` must be included by Cordova framework, not this plugin.

So I guess the error reason is somewhere elese.
http://stackoverflow.com/questions/10714600/cdvplugin-h-file-not-found-in-cordova-as-component-cleaver

Try to install the master branch.

**Comment by johangrobler** [comment]
Hi 

Uninstall plugin and use this

cordova plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"

You might want to user ios@4.0.0 if that does not work

**Comment by hoffination** [comment]
I'm also having a similar issue running on iOS.
I was successfully building on 5.4.1 but had to upgrade for phonegap-plugin-push.
I upgraded to Cordova 6.1.1 and tried ios@4.1.1 and iOS@4.0.0.

I'm not seeing the CDVJSON issue in Xcode 7.2, only the self.webView issues.

```
CompileC build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMaps.o YoRally/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=211 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-generated-files.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-own-target-headers.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-all-target-headers.hmap -iquote /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-project-headers.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator/usr/local/lib/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/UninstalledProducts/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/DerivedSources/i386 -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/DerivedSources -F/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator -FYoRally/Plugins/com.googlemaps.ios -FYoRally/Plugins/cordova-plugin-facebook4 -include /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/sharedpch/YoRally-Prefix-cwpwcqwyfbhasbhkhnbfkmxbohku/YoRally-Prefix.pch -MMD -MT dependencies -MF /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMaps.d --serialize-diagnostics /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMaps.dia -c /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m -o /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMaps.o
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:24:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:28:45: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
    self.pluginScrollView.debugView.webView = self.webView;
                                            ^ ~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:34:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:167:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
        self.mapCtrl.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector 'initWithWebView:'
        Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
                                                          ^~~~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:186:38: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
            self.pluginLayer.webView = self.webView;
                                     ^ ~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector 'initWithWebView:'
                pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
                                                                   ^~~~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares the selector
      'stringByEvaluatingJavaScriptFromString:'
    [self.webView stringByEvaluatingJavaScriptFromString:jsString];
     ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMaps.m:404:34: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable'
      [-Wincompatible-pointer-types]
        self.pluginLayer.webView = self.webView;
                                 ^ ~~~~~~~~~~~~
6 warnings and 3 errors generated.

CompileC build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMapsViewController.o YoRally/Plugins/plugin.google.maps/GoogleMapsViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=211 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-generated-files.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-own-target-headers.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-all-target-headers.hmap -iquote /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/YoRally-project-headers.hmap -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator/usr/local/lib/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/UninstalledProducts/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/DerivedSources/i386 -I/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/DerivedSources -F/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator -FYoRally/Plugins/com.googlemaps.ios -FYoRally/Plugins/cordova-plugin-facebook4 -include /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/sharedpch/YoRally-Prefix-cwpwcqwyfbhasbhkhnbfkmxbohku/YoRally-Prefix.pch -MMD -MT dependencies -MF /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMapsViewController.d --serialize-diagnostics /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMapsViewController.dia -c /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMapsViewController.m -o /Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMapsViewController.o
/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/YoRally/Plugins/plugin.google.maps/GoogleMapsViewController.m:10:9: fatal error: 'Cordova/CDVJSON.h' file not found
#import <Cordova/CDVJSON.h>
        ^


** BUILD FAILED **


The following build commands failed:
	CompileC build/YoRally.build/Debug-iphonesimulator/YoRally.build/Objects-normal/i386/GoogleMaps.o YoRally/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/cordova/build-debug.xcconfig,-project,YoRally.xcodeproj,ARCHS=i386,-target,YoRally,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/jshredder1/YoRallyAuto/ChatApp_0.1/YoRally/platforms/ios/build/sharedpch
```

**Comment by Hirbod** [comment]
@hoffination you need to upgrade using the master version. Delete old plugin version and reinstall. Howto is on first-page wiki

**Comment by hoffination** [comment]
That worked! Thanks!
